# WEB SCRAPING - ASSIGNMENT 4

In [1]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.by import By

import time

Q1.  Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
You need to find following details:

 A) Rank
 
 B) Name
 
 C) Artist
 
 D) Upload date
 
 E) Views

In [2]:
driver  =  webdriver.Chrome(r'C:\Users\user\Downloads\chromedriver_win32 (1)\chromedriver.exe')

In [3]:
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

In [4]:
Ranks=[]
ranks = driver.find_elements("xpath",'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[1]')
for i in ranks:
    Ranks.append(i.text)
len(Ranks)

30

In [5]:
Ranks

['1.',
 '2.',
 '3.',
 '4.',
 '5.',
 '6.',
 '7.',
 '8.',
 '9.',
 '10.',
 '11.',
 '12.',
 '13.',
 '14.',
 '15.',
 '16.',
 '17.',
 '18.',
 '19.',
 '20.',
 '21.',
 '22.',
 '23.',
 '24.',
 '25.',
 '26.',
 '27.',
 '28.',
 '29.',
 '30.']

In [6]:
name=[]

name=[i.text for i in driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[2]')]

len(name)

30

In [7]:
name

['"Baby Shark Dance"[3]',
 '"Despacito"[6]',
 '"Johny Johny Yes Papa"[12]',
 '"Shape of You"[13]',
 '"See You Again"[15]',
 '"Bath Song"[20]',
 '"Phonics Song with Two Words"[21]',
 '"Uptown Funk"[22]',
 '"Learning Colors – Colorful Eggs on a Farm"[23]',
 '"Masha and the Bear – Recipe for Disaster"[24]',
 '"Gangnam Style"[25]',
 '"Wheels on the Bus"[30]',
 '"Dame Tu Cosita"[31]',
 '"Sugar"[32]',
 '"Roar"[33]',
 '"Counting Stars"[34]',
 '"Sorry"[35]',
 '"Thinking Out Loud"[36]',
 '"Axel F"[37]',
 '"Dark Horse"[38]',
 '"Girls Like You"[39]',
 '"Faded"[40]',
 '"Baa Baa Black Sheep"[41]',
 '"Let Her Go"[42]',
 '"Bailando"[43]',
 '"Lean On"[44]',
 '"Perfect"[45]',
 '"Waka Waka (This Time for Africa)"[46]',
 '"Shake It Off"[47]',
 '"Mi Gente"[48]']

In [8]:
artist=[]

artist=[i.text for i in driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[3]')]

len(artist)

30

In [9]:
artist

["Pinkfong Baby Shark - Kids' Songs & Stories",
 'Luis Fonsi',
 'LooLoo Kids',
 'Ed Sheeran',
 'Wiz Khalifa',
 'Cocomelon – Nursery Rhymes',
 'ChuChu TV',
 'Mark Ronson',
 'Miroshka TV',
 'Get Movies',
 'Psy',
 'Cocomelon – Nursery Rhymes',
 'El Chombo',
 'Maroon 5',
 'Katy Perry',
 'OneRepublic',
 'Justin Bieber',
 'Ed Sheeran',
 'Crazy Frog',
 'Katy Perry',
 'Maroon 5',
 'Alan Walker',
 'Cocomelon – Nursery Rhymes',
 'Passenger',
 'Enrique Iglesias',
 'Major Lazer',
 'Ed Sheeran',
 'Shakira',
 'Taylor Swift',
 'J Balvin']

In [10]:
views=[]

views=[i.text for i in driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[4]')]

len(views)

30

In [11]:
views

['11.05',
 '7.93',
 '6.40',
 '5.77',
 '5.59',
 '5.54',
 '4.77',
 '4.65',
 '4.60',
 '4.50',
 '4.50',
 '4.24',
 '4.00',
 '3.74',
 '3.63',
 '3.62',
 '3.57',
 '3.48',
 '3.45',
 '3.32',
 '3.32',
 '3.32',
 '3.31',
 '3.27',
 '3.25',
 '3.24',
 '3.22',
 '3.21',
 '3.19',
 '3.11']

In [12]:
upload=[]

upload=[i.text for i in driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[5]')]

len(upload)

30

In [13]:
upload

['June 17, 2016',
 'January 12, 2017',
 'October 8, 2016',
 'January 30, 2017',
 'April 6, 2015',
 'May 2, 2018',
 'March 6, 2014',
 'November 19, 2014',
 'February 27, 2018',
 'January 31, 2012',
 'July 15, 2012',
 'May 24, 2018',
 'April 5, 2018',
 'January 14, 2015',
 'September 5, 2013',
 'May 31, 2013',
 'October 22, 2015',
 'October 7, 2014',
 'June 16, 2009',
 'February 20, 2014',
 'May 31, 2018',
 'December 3, 2015',
 'June 25, 2018',
 'July 25, 2012',
 'April 11, 2014',
 'March 22, 2015',
 'November 9, 2017',
 'June 4, 2010',
 'August 18, 2014',
 'June 29, 2017']

In [14]:
len(Ranks),len(name),len(artist),len(upload),len(views)

(30, 30, 30, 30, 30)

In [15]:
df=pd.DataFrame({'RANK':Ranks,'Name':name,'Artist':artist,'Upload Date':upload,'Views':views})
df

,RANK,Name,Artist,Upload Date,Views
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",11.05
1,2.,"""Despacito""[6]",Luis Fonsi,"January 12, 2017",7.93
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,"October 8, 2016",6.40
3,4.,"""Shape of You""[13]",Ed Sheeran,"January 30, 2017",5.77
4,5.,"""See You Again""[15]",Wiz Khalifa,"April 6, 2015",5.59
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,"May 2, 2018",5.54
6,7.,"""Phonics Song with Two Words""[21]",ChuChu TV,"March 6, 2014",4.77
7,8.,"""Uptown Funk""[22]",Mark Ronson,"November 19, 2014",4.65
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[23]",Miroshka TV,"February 27, 2018",4.60
9,10.,"""Masha and the Bear – Recipe for Disaster""[24]",Get Movies,"January 31, 2012",4.50
10,11.,"""Gangnam Style""[25]",Psy,"July 15, 2012",4.50
11,12.,"""Wheels on the Bus""[30]",Cocomelon – Nursery Rhymes,"May 24, 2018",4.24
12,13.,"""Dame Tu Cosita""[31]",El Chombo,"April 5, 2018",4.00
13,14.,"""Sugar""[32]",Maroon 5,"January 14, 2015",3.74
14,15.,"""Roar""[33]",Katy Perry,"September 5, 2013",3.63
15,16.,"""Counting Stars""[34]",OneRepublic,"May 31, 2013",3.62
16,17.,"""Sorry""[35]",Justin Bieber,"October 22, 2015",3.57
17,18.,"""Thinking Out Loud""[36]",Ed Sheeran,"October 7, 2014",3.48
18,19.,"""Axel F""[37]",Crazy Frog,"June 16, 2009",3.45
19,20.,"""Dark Horse""[38]",Katy Perry,"February 20, 2014",3.32
20,21.,"""Girls Like You""[39]",Maroon 5,"May 31, 2018",3.32
21,22.,"""Faded""[40]",Alan Walker,"December 3, 2015",3.32
22,23.,"""Baa Baa Black Sheep""[41]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.31
23,24.,"""Let Her Go""[42]",Passenger,"July 25, 2012",3.27
24,25.,"""Bailando""[43]",Enrique Iglesias,"April 11, 2014",3.25
25,26.,"""Lean On""[44]",Major Lazer,"March 22, 2015",3.24
26,27.,"""Perfect""[45]",Ed Sheeran,"November 9, 2017",3.22
27,28.,"""Waka Waka (This Time for Africa)""[46]",Shakira,"June 4, 2010",3.21
28,29.,"""Shake It Off""[47]",Taylor Swift,"August 18, 2014",3.19
29,30.,"""Mi Gente""[48]",J Balvin,"June 29, 2017",3.11

In [16]:
driver.close()

#

Q2.  Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:

 A) Match title (I.e. 1st ODI)

 B) Series

 C) Place
 
 D) Date

 E) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code

In [17]:
driver  =  webdriver.Chrome(r'C:\Users\user\Downloads\chromedriver_win32 (1)\chromedriver.exe')

In [18]:
driver.get("https://www.bcci.tv/")

In [19]:
international = driver.find_element("xpath","/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a")
international.click()

In [20]:
series=[]

match_series=driver.find_elements("xpath",'//div[@class="fixture-card-top"]')
for i in match_series[0:6]:
    series.append(i.text.split('\n')[0])
    
len(series)

5

In [21]:
series

['INDIA TOUR OF ZIMBABWE ODI SERIES 2022',
 'INDIA TOUR OF ZIMBABWE ODI SERIES 2022',
 'INDIA TOUR OF ZIMBABWE ODI SERIES 2022',
 'ASIA CUP 2022',
 'ASIA CUP 2022']

In [22]:
titles=[]

match_titles=driver.find_elements("xpath",'//div[@class="fixture-card-mid d-flex align-items-center justify-content-between"]')
for i in match_titles:
    titles.append(i.text)
len(titles)

5

In [23]:
titles

['Zimbabwe\nvs\nIndia',
 'Zimbabwe\nvs\nIndia',
 'Zimbabwe\nvs\nIndia',
 'India\nvs\nPakistan',
 'India\nvs\nQualifier-1']

In [24]:
places=[]

place=driver.find_elements("xpath",'//div[@class="fix-place ng-binding ng-scope"]')
for i in place:
    places.append(i.text)
len(places)

5

In [25]:
places

['1st ODI - Harare Sports Club, Harare',
 '2nd ODI - Harare Sports Club, Harare',
 '3rd ODI - Harare Sports Club, Harare',
 '1st T20I - Dubai International Cricket Stadium, Dubai',
 '2nd T20I - Dubai International Cricket Stadium, Dubai']

In [26]:
date=[]

match_date=driver.find_elements("xpath",'//div[@class="match-card-left match-schedule"]')
for i in match_date:
    date.append(i.text)
len(date)

5

In [27]:
date

['18 AUG 2022', '20 AUG 2022', '22 AUG 2022', '28 AUG 2022', '31 AUG 2022']

In [28]:
time=[]

match_time=driver.find_elements("xpath",'//div[@class="match-card-right match-schedule "]')
for i in match_time:
    time.append(i.text)
len(time)

5

In [29]:
time

['12:45 PM IST', '12:45 PM IST', '12:45 PM IST', '7:30 PM IST', '7:30 PM IST']

In [30]:
print(len(titles),len(series),len(places),len(date),len(time))

5 5 5 5 5

In [31]:
df = pd.DataFrame({'Match Title':titles,'Series':series,'Place':places,'Date':date,'Time':time})
df

,Match Title,Series,Place,Date,Time
0,Zimbabwe\nvs\nIndia,INDIA TOUR OF ZIMBABWE ODI SERIES 2022,"1st ODI - Harare Sports Club, Harare",18 AUG 2022,12:45 PM IST
1,Zimbabwe\nvs\nIndia,INDIA TOUR OF ZIMBABWE ODI SERIES 2022,"2nd ODI - Harare Sports Club, Harare",20 AUG 2022,12:45 PM IST
2,Zimbabwe\nvs\nIndia,INDIA TOUR OF ZIMBABWE ODI SERIES 2022,"3rd ODI - Harare Sports Club, Harare",22 AUG 2022,12:45 PM IST
3,India\nvs\nPakistan,ASIA CUP 2022,1st T20I - Dubai International Cricket Stadium...,28 AUG 2022,7:30 PM IST
4,India\nvs\nQualifier-1,ASIA CUP 2022,2nd T20I - Dubai International Cricket Stadium...,31 AUG 2022,7:30 PM IST

In [32]:
driver.close()

#

Q3.  Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:

 A) Name
 
 B) Description

Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [33]:
import time

In [34]:
driver = webdriver.Chrome(r"C:/Users/user/Downloads/chromedriver_win32 (1)/chromedriver.exe")
driver.get("https://www.guru99.com/")
time.sleep(5)

In [35]:
selenium=driver.find_element("xpath",'/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[2]/div[1]/div/ul[1]/li[3]/a')
selenium.click()

In [36]:
tutorial=driver.find_element("xpath",'/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a')
tutorial.click()

In [37]:
name=[]

name=[i.text for i in driver.find_elements(By.XPATH,'//table[@class="table table-striped"][1]/tbody/tr/td[1]')]

len(name)

41

In [38]:
name

['ElementNotVisibleException',
 'ElementNotSelectableException',
 'NoSuchElementException',
 'NoSuchFrameException',
 'NoAlertPresentException',
 'NoSuchWindowException',
 'StaleElementReferenceException',
 'SessionNotFoundException',
 'TimeoutException',
 'WebDriverException',
 'ConnectionClosedException',
 'ElementClickInterceptedException',
 'ElementNotInteractableException',
 'ErrorInResponseException',
 'ErrorHandler.UnknownServerException',
 'ImeActivationFailedException',
 'ImeNotAvailableException',
 'InsecureCertificateException',
 'InvalidArgumentException',
 'InvalidCookieDomainException',
 'InvalidCoordinatesException',
 'InvalidElementStateExceptio',
 'InvalidSessionIdException',
 'InvalidSwitchToTargetException',
 'JavascriptException',
 'JsonException',
 'NoSuchAttributeException',
 'MoveTargetOutOfBoundsException',
 'NoSuchContextException',
 'NoSuchCookieException',
 'NotFoundException',
 'RemoteDriverServerException',
 'ScreenshotException',
 'SessionNotCreatedException',
 'UnableToSetCookieException',
 'UnexpectedTagNameException',
 'UnhandledAlertException',
 'UnexpectedAlertPresentException',
 'UnknownMethodException',
 'UnreachableBrowserException',
 'UnsupportedCommandException']

In [39]:
desc=[]

desc=[i.text for i in driver.find_elements(By.XPATH,'//table[@class="table table-striped"][1]/tbody/tr/td[2]')]

len(desc)

41

In [40]:
desc

['This type of Selenium exception occurs when an existing element in DOM has a feature set as hidden.',
 'This Selenium exception occurs when an element is presented in the DOM, but you can be able to select. Therefore, it is not possible to interact.',
 'This Exception occurs if an element could not be found.',
 'This Exception occurs if the frame target to be switched to does not exist.',
 'This Exception occurs when you switch to no presented alert.',
 'This Exception occurs if the window target to be switch does not exist.',
 'This Selenium exception occurs happens when the web element is detached from the current DOM.',
 'The WebDriver is acting after you quit the browser.',
 'Thrown when there is not enough time for a command to be completed. For Example, the element searched wasn’t found in the specified time.',
 'This Exception takes place when the WebDriver is acting right after you close the browser.',
 'This type of Exception takes place when there is a disconnection in the driver.',
 'The command may not be completed as the element receiving the events is concealing the element which was requested clicked.',
 'This Selenium exception is thrown when any element is presented in the DOM. However, it is impossible to interact with such an element.',
 'This happens while interacting with the Firefox extension or the remote driver server.',
 'Exception is used as a placeholder in case if the server returns an error without a stack trace.',
 'This expectation will occur when IME engine activation has failed.',
 'It takes place when IME support is unavailable.',
 'Navigation made the user agent to hit a certificate warning. This can cause by an invalid or expired TLS certificate.',
 'It occurs when an argument does not belong to the expected type.',
 'This happens when you try to add a cookie under a different domain instead of current URL.',
 'This type of Exception matches an interacting operation that is not valid.',
 'It occurs when command can’t be finished when the element is invalid.',
 'This Exception took place when the given session ID is not included in the list of active sessions. It means the session does not exist or is inactive either.',
 'This occurs when the frame or window target to be switched does not exist.',
 'This issue occurs while executing JavaScript given by the user.',
 'It occurs when you afford to get the session when the session is not created.',
 'This kind of Exception occurs when the attribute of an element could not be found.',
 'It takes place if the target provided to the ActionChains move() methodology is not valid. For Example, out of the document.',
 'ContextAware does mobile device testing.',
 'This Exception occurs when no cookie matching with the given pathname found for all the associated cookies of the currently browsing document.',
 'This Exception is a subclass of WebDriverException. This will occur when an element on the DOM does not exist.',
 'This Selenium exception is thrown when the server is not responding because of the problem that the capabilities described are not proper.',
 'It is not possible to capture a screen.',
 'It happens when a new session could not be successfully created.',
 'This occurs if a driver is unable to set a cookie.',
 'Happens if a support class did not get a web element as expected.',
 'This expectation occurs when there is an alert, but WebDriver is not able to perform Alert operation.',
 'It occurs when there is the appearance of an unexpected alert.',
 'This Exception happens when the requested command matches with a known URL but and not matching with a methodology for a specific URL.',
 'This Exception occurs only when the browser is not able to be opened or crashed because of some reason.',
 'This occurs when remote WebDriver does n’t send valid commands as expected.']

In [41]:
len(name),len(desc)

(41, 41)

In [42]:
df=pd.DataFrame({'NAME':name,'DESCRIPTION':desc})
df

,NAME,DESCRIPTION
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

In [43]:
driver.close()

#

Q4.  Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:

  A) Rank
  
  B) State
  
  C) GSDP(18-19)
   
  D) GSDP(17-18)

  E) Share(2017)
  
  F) GDP($ billion)
 
Note: - From statisticstimes home page you have to reach to economy page through code.

In [48]:
driver  =  webdriver.Chrome(r'C:\Users\user\Downloads\chromedriver_win32 (1)\chromedriver.exe')
driver.get("http://statisticstimes.com/")
time.sleep(5)

In [49]:
eco_btn=driver.find_element("xpath","/html/body/div[2]/div[1]/div[2]/div[2]/button")
eco_btn.click()

eco_ind_btn=driver.find_element("xpath","/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]")
eco_ind_btn.click()

In [50]:
rank=[]
ranks=driver.find_elements("xpath",'//td[@class="data1"]')
for i in ranks[0:34]:
    rank.append(i.text)
len(rank)

34

In [51]:
rank

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '']

In [52]:
name=[]
nam=driver.find_elements("xpath",'//td[@class="name"]')
for i in nam[0:34]:
    name.append(i.text)
len(name)

34

In [53]:
name

['Maharashtra',
 'Tamil Nadu',
 'Uttar Pradesh',
 'Gujarat',
 'Karnataka',
 'West Bengal',
 'Rajasthan',
 'Andhra Pradesh',
 'Telangana',
 'Madhya Pradesh',
 'Kerala',
 'Delhi',
 'Haryana',
 'Bihar',
 'Punjab',
 'Odisha',
 'Assam',
 'Chhattisgarh',
 'Jharkhand',
 'Uttarakhand',
 'Jammu & Kashmir',
 'Himachal Pradesh',
 'Goa',
 'Tripura',
 'Chandigarh',
 'Puducherry',
 'Meghalaya',
 'Sikkim',
 'Manipur',
 'Nagaland',
 'Arunachal Pradesh',
 'Mizoram',
 'Andaman & Nicobar Islands',
 'India']

In [54]:
gdp1=[]

gdp1=[i.text for i in  driver.find_elements(By.XPATH,'//table[@class="display dataTable"][1]/tbody/tr/td[3]')]

len(gdp1)

66

In [55]:
gdp1[0:34]

['-',
 '1,845,853',
 '1,687,818',
 '-',
 '1,631,977',
 '1,253,832',
 '1,020,989',
 '972,782',
 '969,604',
 '906,672',
 '-',
 '856,112',
 '831,610',
 '611,804',
 '574,760',
 '521,275',
 '-',
 '329,180',
 '328,598',
 '-',
 '-',
 '165,472',
 '80,449',
 '55,984',
 '-',
 '38,253',
 '36,572',
 '32,496',
 '31,790',
 '-',
 '-',
 '26,503',
 '-',
 '-']

In [56]:
gsdp=[]
gdp=driver.find_elements("xpath",'//td[@class="data sorting_1"]')
for i in gdp[0:34]:
    gsdp.append(i.text)
len(gsdp)

34

In [57]:
gsdp

['2,632,792',
 '1,630,208',
 '1,584,764',
 '1,502,899',
 '1,493,127',
 '1,089,898',
 '942,586',
 '862,957',
 '861,031',
 '809,592',
 '781,653',
 '774,870',
 '734,163',
 '530,363',
 '526,376',
 '487,805',
 '315,881',
 '304,063',
 '297,204',
 '245,895',
 '155,956',
 '153,845',
 '73,170',
 '49,845',
 '42,114',
 '34,433',
 '33,481',
 '28,723',
 '27,870',
 '27,283',
 '24,603',
 '22,287',
 '-',
 '2,332,992']

In [58]:
share=[]

share=[i.text for i in  driver.find_elements(By.XPATH,'//table[@class="display dataTable"][1]/tbody/tr/td[5]')]

len(share)

66

In [59]:
share[0:34]

['13.94%',
 '8.63%',
 '8.39%',
 '7.96%',
 '7.91%',
 '5.77%',
 '4.99%',
 '4.57%',
 '4.56%',
 '4.29%',
 '4.14%',
 '4.10%',
 '3.89%',
 '2.81%',
 '2.79%',
 '2.58%',
 '1.67%',
 '1.61%',
 '1.57%',
 '1.30%',
 '0.83%',
 '0.81%',
 '0.39%',
 '0.26%',
 '0.22%',
 '0.18%',
 '0.18%',
 '0.15%',
 '0.15%',
 '0.14%',
 '0.13%',
 '0.12%',
 '-',
 '13.97%']

In [60]:
GDP=[]

GDP=[i.text for i in  driver.find_elements(By.XPATH,'//table[@class="display dataTable"][1]/tbody/tr/td[6]')]

len(GDP)

66

In [61]:
GDP[0:34]

['399.921',
 '247.629',
 '240.726',
 '228.290',
 '226.806',
 '165.556',
 '143.179',
 '131.083',
 '130.791',
 '122.977',
 '118.733',
 '117.703',
 '111.519',
 '80.562',
 '79.957',
 '74.098',
 '47.982',
 '46.187',
 '45.145',
 '37.351',
 '23.690',
 '23.369',
 '11.115',
 '7.571',
 '6.397',
 '5.230',
 '5.086',
 '4.363',
 '4.233',
 '4.144',
 '3.737',
 '3.385',
 '-',
 '-']

In [62]:
len(rank),len(name),len(gdp1[0:34]),len(gsdp),len(share[0:34]),len(GDP[0:34])

(34, 34, 34, 34, 34, 34)

In [63]:
df=pd.DataFrame({'RANK':rank,'NAME':name,'GSDP 2019-20':gdp1[0:34],'GSDP 2018-19':gsdp,'SHARE':share[0:34],'GDP($billion)':GDP[0:34]})
df

,RANK,NAME,GSDP 2019-20,GSDP 2018-19,SHARE,GDP($billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-
33,,India,-,"2,332,992",13.97%,-

In [64]:
driver.close()

#

5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
 
 A) Repository title

 B) Repository description
 
 C) Contributors count

 D) Language used

Note: - From the home page you have to click on the trending option from Explore menu through code.

In [71]:
driver  =  webdriver.Chrome(r'C:\Users\user\Downloads\chromedriver_win32 (1)\chromedriver.exe')

In [72]:
driver.get('https://github.com/')

In [73]:
explore_btn=driver.find_element("xpath",'/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary')
explore_btn.click()

In [74]:
trend_btn=driver.find_element("xpath",'/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a')
trend_btn.click()

In [75]:
repo_title=[]
repo_desc=[]
contributor_count=[]
lang_used=[]
time.sleep(2)

In [79]:
time.sleep(4)    
for j in driver.find_elements(By.XPATH,'//h1[@class="h3 lh-condensed"]'):
        repo_title.append(j.text)
for k in driver.find_elements(By.XPATH,'//p[@class="col-9 color-fg-muted my-1 pr-4"]'):
        repo_desc.append(k.text)
for l in driver.find_elements(By.XPATH,'//span[@class="d-inline-block mr-3"]'):
        contributor_count.append(l.text)
for m in driver.find_elements(By.XPATH,'//span[@itemprop="programmingLanguage"]'):
        lang_used.append(m.text)

In [80]:
print(len(repo_title[0:21]),len(repo_desc[0:21]),len(contributor_count[0:21]),len(lang_used))

21 21 21 21

In [81]:
df=pd.DataFrame({'Repository Title':repo_title[0:21],'Repository Description':repo_desc[0:21],'Contributors Count':contributor_count[0:21],'Language Used':lang_used})
df

,Repository Title,Repository Description,Contributors Count,Language Used
0,toeverything / AFFiNE,There can be more than Notion and Miro. Affine...,Built by,TypeScript
1,jwasham / coding-interview-university,A complete computer science study plan to beco...,Built by,JavaScript
2,iptv-org / iptv,Collection of publicly available IPTV channels...,Built by,C
3,ventoy / Ventoy,A new bootable USB solution.,Built by,C++
4,MarlinFirmware / Marlin,Marlin is an optimized firmware for RepRap 3D ...,Built by,Go
5,Dreamacro / clash,A rule-based tunnel in Go.,Built by,Python
6,arthurspk / guiadevbrasil,GUIA EXTENSO DE PROGRAMAÇÃO:,Built by,Python
7,donnemartin / system-design-primer,Learn how to design large-scale systems. Prep ...,Built by,TypeScript
8,MatrixTM / MHDDoS,"Best DDoS Attack Script Python3, (Cyber / DDos...",Built by,Python
9,t3-oss / create-t3-app,Quickest way to start a new web app with full ...,Built by,CSS
10,punk-security / dnsReaper,dnsReaper - subdomain takeover tool for attack...,Built by,Python
11,juliocesarfort / public-pentesting-reports,Curated list of public penetration test report...,Built by,Swift
12,facebookresearch / ParlAI,A framework for training and evaluating AI mod...,Built by,JavaScript
13,utmapp / UTM,Virtual machines for iOS and macOS,Built by,JavaScript
14,theboy181 / switch-ptchtxt-mods,30 Days of React challenge is a step by step g...,Built by,Python
15,Asabeneh / 30-Days-Of-React,The open-source repo for docs.github.com,Built by,HTML
16,github / docs,A curated list of awesome Machine Learning fra...,Built by,Python
17,josephmisiti / awesome-machine-learning,计算机自学指南,Built by,HTML
18,PKUFlyingPig / cs-self-learning,Create Disco Diffusion artworks in one line,Built by,Jupyter Notebook
19,jina-ai / discoart,Gather and update all available and newest CVE...,Built by,C++
20,trickest / cve,Notes about courses Dive into Deep Learning by...,Built by,Python

In [82]:
driver.close()

#

 Q6.  Scrape the details of top 100 songs on billiboard.com.
Url = https:/www.billboard.com/
You have to find the following details:

 A) Song name

 B) Artist name

 C) Last week rank

 D) Peak rank

 E) Weeks on board

Note: - From the home page you have to click on the charts option then hot 100-page link through code

In [87]:
driver  =  webdriver.Chrome(r'C:\Users\user\Downloads\chromedriver_win32 (1)\chromedriver.exe')

In [88]:
driver.get('https:/www.billboard.com/')

In [89]:
charts=driver.find_element("xpath",'/html/body/div[3]/div[6]/div/div/div/ul/li[1]/h3/button')
charts.click()

In [90]:
billboards_hotlist=driver.find_element("xpath",'/html/body/div[3]/div[6]/div/div/div/ul/li[1]/ul/li[2]/a')
billboards_hotlist.click()

In [91]:
songs_100=[]
artist_100=[]
last_week=[]
peak_pos=[]
wks_chart=[]

In [92]:
time.sleep(4)
for i in driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]'):
    songs_100.append(i.text.split('\n')[0])
for j in driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]'):
    artist_100.append(j.text.split('\n')[1])
for k in driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]'):
    last_week.append(k.text.split('\n')[2])
for l in driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]'):
     peak_pos.append(l.text.split('\n')[3])
for m in driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]'):
    wks_chart.append(m.text.split('\n')[4])

In [93]:
len(songs_100),len(artist_100),len(last_week), len(peak_pos),len(wks_chart)

(100, 100, 100, 100, 100)

In [94]:
df=pd.DataFrame({'SONG':songs_100,'ARTIST':artist_100,'LAST WEEK RANK':last_week,'PEAK RANK':peak_pos,'WEEKS ON BOARD':wks_chart})
df

,SONG,ARTIST,LAST WEEK RANK,PEAK RANK,WEEKS ON BOARD
0,About Damn Time,Lizzo,1,1,15
1,As It Was,Harry Styles,2,1,17
2,Running Up That Hill (A Deal With God),Kate Bush,3,3,29
3,First Class,Jack Harlow,4,1,16
4,Wait For U,Future Featuring Drake & Tems,5,1,13
...,...,...,...,...,...
95,Te Felicito,Shakira & Rauw Alejandro,95,67,8
96,Are You Entertained,Russ & Ed Sheeran,-,97,1
97,"Bzrp Music Sessions, Vol. 52",Bizarrap & Quevedo,-,98,1
98,Right On,Lil Baby,97,13,15
99,La Corriente,Bad Bunny & Tony Dize,99,32,9

In [95]:
driver.close()

#

Q7.  Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/hr-recruiters-consultants
You have to find the following details:

 A) Name

 B) Designation

 C) Company

 D) Skills they hire for
 
 E) Location
 
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code.

In [96]:
driver  =  webdriver.Chrome(r'C:\Users\user\Downloads\chromedriver_win32 (1)\chromedriver.exe')

In [97]:
driver.get('https://www.naukri.com/hr-recruiters-consultants')

In [98]:
search_bar=driver.find_element("xpath",'/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/div/div[1]/div[1]/div[2]/input')
search_bar.send_keys('Data Science')

In [99]:
search = driver.find_element("xpath",'//button[@class="fl qsbSrch blueBtn"]')
search.click()

In [100]:
name=[]
names=driver.find_elements("xpath",'//div[@class="recInfo"]')
for i in names:
    name.append(i.text.split('\n')[0])
len(name)

50

In [101]:
name

['Aakash Harit',
 'shravan Kumar Gaddam',
 'MARSIAN Technologies LLP',
 'Anik Agrawal',
 'subhas patel',
 'Abhishek - Only Analytics Hiring - India and',
 'Institute for Financial Management and Resear',
 'Balu Ramesh',
 'Asif Lucknowi',
 'InstaFinancials',
 'Vaishnavi Kudalkar',
 'Priyanka Akiri',
 'Kalpana Dumpala',
 'Mubarak',
 'Kushal Rastogi',
 'Mahesh Babu Channa',
 'Kapil Devang',
 'Sakshi Chhikara',
 'Ruchi Dhote',
 'Manisha Yadav',
 'Riya Rajesh',
 'Rashmi Bhattacharjee',
 'Faizan Kareem',
 'Rithika dadwal',
 'Sandhya Khandagale',
 'Shaun Rao',
 'Azahar Shaikh',
 'Manas',
 'kumar',
 'Sunil Vedula',
 'Rajat Kumar',
 'Dhruv Dev Dubey',
 'Jayanth N',
 'Avodha',
 'Priya Khare',
 'Amit Sharma',
 'Kanan',
 'Shashikant Chaudhary',
 'Brad',
 'Rutuja Pawar',
 'Madhusudhan Sridhar',
 'Ankit Sinha',
 'Gaurav Chouhan',
 'Rashi Kacker',
 'Ashwini',
 'Balaji Kolli',
 'Rajani Nagaraj',
 'ROHIT Kumar',
 'Amir Chowdhury',
 'SREEDHAR']

In [102]:
design=[]
desg=driver.find_elements("xpath",'//div[@class="recInfo"]')
for i in desg:
    design.append(i.text.split('\n')[1])
len(design)

50

In [103]:
design

['HR Manager',
 'Company Recruiter',
 'Company HR',
 'Company Recruiter',
 'Founder CEO',
 'Recruitment Lead Consultant',
 'Programme Manager',
 'HR Administrator',
 'Director',
 'Human Resource',
 'HR Executive',
 'HR Manager',
 'Executive Hiring',
 'Company HR',
 'Company HR',
 'HR Team Lead',
 'HR Manager',
 'Assistant Manager HR',
 'Senior Executive Talent Acquisition',
 'HR Executive',
 'Manager Talent Acquisition',
 'HR Head',
 'HR MANAGER',
 'HR Recruiter',
 'HR Recruiter',
 'Manager Human Resources',
 'Company Recruiter',
 'Lead Talent acquisition',
 'Proprietor',
 'CEO',
 'Founder CEO',
 'Company Recruitment Head',
 'Project Manager',
 'Business Development Associate',
 'Senior Manager',
 'Consultant',
 'senior technology instructor',
 'HR Recruiter/HR Excutive',
 'Manager, Technical Recruiting',
 'Technical Recruiter',
 'Erp Implementer',
 'Head Analytics',
 'Chief Technical Officer',
 'Sr Product Manager',
 'Director Global Delivery',
 'Co Founder',
 'HR Manager',
 'Architect',
 'Managing Partner',
 'Recruitment Consultant']

In [104]:
company=[]
coms=driver.find_elements("xpath",'//div[@class="recInfo"]')
for i in coms:
    company.append(i.text.split('\n')[2])
len(company)

50

In [105]:
company

['Data Science Network',
 'Shore Infotech India Pvt. Ltd',
 'MARSIAN Technologies LLP',
 'Enerlytics Software Solutions Pvt Ltd',
 'LibraryXProject',
 'Apidel Technologies Division of Transpower',
 'IFMR',
 'Techvantage Systems Pvt Ltd',
 'Weupskill- Live Wire India',
 'CBL Data Science Private Limited',
 'Codeachive learning',
 'Infinitive Software Solutions',
 'Innominds Software',
 'MoneyTap',
 'QuantMagnum Technologies Pvt. Ltd.',
 'SocialPrachar.com',
 'BISP Solutions',
 'BIZ INFOTECNO PRIVATE LIMITED',
 'Bristlecone India Ltd',
 'Easi Tax',
 'Novelworx Digital Solutions',
 'AXESTRACK SOFTWARE SOLUTIONS PRIVATE...',
 'FirstTech Consaltants Pvt.Ltd',
 'Affine Analytics',
 'Compumatrice Multimedia Pvt Ltd',
 'Exela Technologies',
 'NEAL ANALYTICS SERVICES PVT LTD',
 'Autumn Leaf Consulting Services Private...',
 'trainin',
 'Nanoprecise Sci Corp',
 'R.S Consultancy &amp; Services',
 'Confidential',
 'Dollarbird Information Services Pvt, Ltd',
 'Nikitha Palaparthi',
 'Independent Consultant',
 'ASCO consulting',
 'NY INST',
 '3D India Staffing Research &amp; Consulting...',
 'O.C. Tanner',
 'Demand Matrix',
 'MADHUSUDHAN SRIDHAR',
 'Suntech Global',
 'Strategic Consulting Lab',
 'Impel Labs Pvt. Ltd.',
 'MRP Advisers',
 'Saras Solutions India Pvt Ltd',
 'WildJasmine',
 'LNT Private Limited',
 'Granular.ai',
 'JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED']

In [106]:
locn=[]
locs=driver.find_elements("xpath",'//div[@class="recInfo"]')
for i in locs:
    locn.append(i.text.split('\n')[3])
len(locn)

50

In [107]:
locn

['Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Ahmedabad',
 'UK - (london)',
 'Vadodara / Baroda',
 'Chennai',
 'Trivandrum',
 'Indore',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Hyderabad',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Hyderabad / Secunderabad',
 'Bhopal',
 'Chandigarh',
 'Pune',
 'Navi Mumbai',
 'Cochin',
 'Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Pune',
 'Pune',
 'Pune',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore',
 'Skills/Roles I hire for :',
 'Delhi',
 'Bengaluru / Bangalore',
 'Mysoru / Mysore',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'New Delhi',
 'Chennai',
 'Aligarh',
 'Salt Lake City',
 'Pune',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Indore',
 'Bengaluru / Bangalore',
 'MYSORE',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Skills/Roles I hire for :',
 'Hyderabad / Secunderabad']

In [108]:
skills=[]
skill=driver.find_elements("xpath",'//div[@class="hireSec highlightable"]')
for i in skill:
    skills.append(i.text)
len(skills)

50

In [109]:
skills

['Classic ASP Developer, Internet Marketing Professional, Data Science SME, Content Writers, SEO Professional, Revenue Professional',
 '.Net, Java, Data Science, Linux Administration, Sql Server Development, Winforms, Wcf Services, Wpf, Telecom Engineering, Technical Management, Software',
 'Data Science, Artificial Intelligence, Machine Learning, Business Analytics, Deep Learning, statistics, Data Analytics, Data Analysis, support vector machine',
 'Mean Stack, javascript, angularjs, mongodb, Web Services, rest, express, Node.js, Big Data, iot, Data Science, Cloud Computing, saas, Aws',
 'Hadoop, Spark, Digital Strategy, Data Architecture, Command Center, Cdp, Dmp, Kafka, Data Science, Data Analysis, Big Data Analytics, Real Time Analysis, SQL',
 'Analytics, Business Intelligence, Business Analytics, Predictive Modeling, Predictive Analytics, Data Science, Data Analysis, Data Analytics, Big Data, Big',
 'Data Science',
 'Machine Learning, algorithms, Go Getter, Computer Science, spark, Big Data, hdfs, sql, cassandra, hadoop, python, scala, java, Data Science, Front End',
 'Technical Training, Software Development, Presentation Skills, B.tech, M.tech, B.e., mca, msc, Computer Science, freshers, jobs in indore, Data Science, itil',
 'Software Development, It Sales, Account Management, Data Analysis, Customer Service, Sr, Software Engineering, Mvc, Ajax, Asp.net, Html, C#, Javascript',
 'Data Science, Python, Data Analytics',
 'Oracle Dba, Data Science, Data Warehousing, ETL, Jupyter, Numpy, Data Transformation, Snowflake, Teradata, Python, Data Manipulation, Relational Databases',
 'Qa, Ui/ux, Java Developer, Java Architect, C++/qt, Php, Lamp, Api, J2ee, Java, Soa, Esb, Middleware, Bigdata Achitect, Hadoop Architect, Deep',
 'Business Intelligence, Data Warehousing, Data Science, Business Analytics, Customer Support, Business Reporting, Bi',
 'Office Administration, Hr Administration, telecalling, client relationship management, Client Acquisition, Sales, Reception, HR, Recruitment, Onboarding, Human',
 'Social Media, digital media maketing, seo, smm, smo, sem, Content Wirting, social media marketing, social media manager, digital media marketing manager',
 'Big Data, Hadoop, Data Analytics, Data Science',
 'React.js, Data Science, Java, Front End, Business Analytics, Backend, Tableau, Python, Qa Testing, Automation Testing',
 'Qlikview, Qlik Sense, Microsoft Azure, Power Bi, Data Science, Machine Learning',
 'Telecalling, Client Interaction, Marketing, Research, Web Development, Social Media Marketing, Data Entry Operation, Excel, Ms Office, Invoicing',
 'Data Science',
 'Corporate Sales, Software Development, Software Sales, Marketing, Creative Designing, Corporate Planning, Senior Management, Crm, Client Relationship',
 'Data Analytics, Data Science, Machine Learning, Deep Learning, Nlp, Data Mining, Python, R, Database Administration, Text Mining',
 'Data Science, Machine Learning, Python, R, Deep Learning, Big Data, Hadoop',
 'Big Data, Data Science, Artificial Intelligence, Hadoop, Ui Development, Php, Freelancing, .Net, Software Testing, Sap, Leadership Hiring',
 'Java, Net, Angularjs, Hr, Infrastructure, Management, Project Management, Business Analysis, Data Science, Information Technology, Technology',
 'Data Science, Artificial Intelligence, Machine Learning, Data Analytics',
 'Software Architecture, Vp Engineering, Product Management, analytics, Data Science, Node.js, Principal Engineer, Big Data, python, angularjs, React.js',
 'Data Science, Hadoop, Rpas, Devops, Python, Aws, Teaching, Big Data',
 'Signal Processing, Machine Learning, Neural Networks, Data Science, Predictive Analytics, Time Series Analysis, Data Visualization, Technical Leadership, Data',
 'Web Technologies, Project Management, Software Architecture, Data Science, Object Oriented Programming, Computer Science, Electrical Engineering, Architecture',
 'Server Administartion, Verilog, Vhdl, Digital Marketing, Market Research, Property Research, Legal, It And Non It Recruitment, Logistics, Supply Chain, Bfsi',
 'Data Analytics, Managed Services, Team Leading, python, Machine Learning, Google Analytics, Dmp, Aws, Campaign Analytics, Digital Campaigns, Audience',
 'Ethical Hacking, Security Operations Center, SOC, Managed Services, Data Science, Machine Learning, Artificial Intelligence, Operations Research, Education',
 'Data Science, Artificial Intelligence, analytics, Business Intelligence, python, tableau, Power Bi, qlikview, sql, Data Warehousing, Data Visualization',
 'Machine Learning, Artificial Intelligence, Data Science, Software Engineering, Software Development, Graduate Engineer Trainee, Fresher, Data Analytics, Java',
 'C, C++, Artificial Intelligence, Python, Php, Web Development, Matlab, Data Science, Augmented Reality, C C++',
 'Relationship Management, Retail Sales, Private Banking, Mutual Funds, NISM, Equity, Finance, Financial Products, Financial Services, Verbal, Written',
 'Data Science, Software Engineering',
 'Data Science, Big Data Analytics, Digital Marketing, Content Writing, Ui Development, Database Development, Qa Automation, Python, Project Management',
 'Data Science, Recruitment, Salary',
 'B.Tech, Tableau, Statistics, R, Analytics, Time Series, Data Science, Business Solutions, SQL, Technical Skills, SSAS, SQL Server, Analysis Services, Qlikview',
 'Software Development, Business Intelligence, Big Data Analytics, Database Administration, Data Science, Microsoft Azure, Spark, Cassandra, Object Oriented',
 'Data Science, Node.js, Angularjs',
 'Data Science, Media Marketing, Resource Planning, Managed Services, Display Advertising, Machine Learning, Python, Etl, Sql',
 'Data Analysis, Learning, Data Science, Computer Science, Communication Skills',
 'Java, Hadoop, R, Machine Learning, Spark, Flume, Hdfs, Data Mining, Sas, Big, Data Science, Cloudera, Impala, Bigdata',
 'Software Development, Core Java, Unit Testing, Customer Experience, Problem Solving, Communication Skills, Mysql, Data Science, Sales Management, Analytics',
 'Machine Learning, Data Science, Product Management, New Product, Data Analysis, Computer Vision, Deep Learning, Python, Remote Sensing',
 'Data Science, Machine Learning, Big Data Analytics, Spark, Python, R, Networking, Network Engineering, Placement, Training, Sql, Marketing, Mainframes, All']

In [110]:
len(name),len(design),len(company),len(locn),len(skills)

(50, 50, 50, 50, 50)

In [111]:
df=pd.DataFrame({'NAME':name,'DESIGNATION':design,'COMPANY':company,'LOCATION':locn,'SKILLS':skills})
df

,NAME,DESIGNATION,COMPANY,LOCATION,SKILLS
0,Aakash Harit,HR Manager,Data Science Network,Delhi,"Classic ASP Developer, Internet Marketing Prof..."
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,Hyderabad / Secunderabad,".Net, Java, Data Science, Linux Administration..."
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,Pune,"Data Science, Artificial Intelligence, Machine..."
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,Ahmedabad,"Mean Stack, javascript, angularjs, mongodb, We..."
4,subhas patel,Founder CEO,LibraryXProject,UK - (london),"Hadoop, Spark, Digital Strategy, Data Architec..."
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Vadodara / Baroda,"Analytics, Business Intelligence, Business Ana..."
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Chennai,Data Science
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Trivandrum,"Machine Learning, algorithms, Go Getter, Compu..."
8,Asif Lucknowi,Director,Weupskill- Live Wire India,Indore,"Technical Training, Software Development, Pres..."
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,Bengaluru / Bangalore,"Software Development, It Sales, Account Manage..."
10,Vaishnavi Kudalkar,HR Executive,Codeachive learning,Mumbai,"Data Science, Python, Data Analytics"
11,Priyanka Akiri,HR Manager,Infinitive Software Solutions,Hyderabad,"Oracle Dba, Data Science, Data Warehousing, ET..."
12,Kalpana Dumpala,Executive Hiring,Innominds Software,Hyderabad / Secunderabad,"Qa, Ui/ux, Java Developer, Java Architect, C++..."
13,Mubarak,Company HR,MoneyTap,Bengaluru / Bangalore,"Business Intelligence, Data Warehousing, Data ..."
14,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,Mumbai,"Office Administration, Hr Administration, tele..."
15,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Hyderabad / Secunderabad,"Social Media, digital media maketing, seo, smm..."
16,Kapil Devang,HR Manager,BISP Solutions,Bhopal,"Big Data, Hadoop, Data Analytics, Data Science"
17,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,Chandigarh,"React.js, Data Science, Java, Front End, Busin..."
18,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,Pune,"Qlikview, Qlik Sense, Microsoft Azure, Power B..."
19,Manisha Yadav,HR Executive,Easi Tax,Navi Mumbai,"Telecalling, Client Interaction, Marketing, Re..."
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Cochin,Data Science
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Delhi,"Corporate Sales, Software Development, Softwar..."
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,Hyderabad / Secunderabad,"Data Analytics, Data Science, Machine Learning..."
23,Rithika dadwal,HR Recruiter,Affine Analytics,Pune,"Data Science, Machine Learning, Python, R, Dee..."
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,Pune,"Big Data, Data Science, Artificial Intelligenc..."
25,Shaun Rao,Manager Human Resources,Exela Technologies,Pune,"Java, Net, Angularjs, Hr, Infrastructure, Mana..."
26,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,Pune,"Data Science, Artificial Intelligence, Machine..."
27,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,Bengaluru / Bangalore,"Software Architecture, Vp Engineering, Product..."
28,kumar,Proprietor,trainin,Bengaluru / Bangalore,"Data Science, Hadoop, Rpas, Devops, Python, Aw..."
29,Sunil Vedula,CEO,Nanoprecise Sci Corp,Skills/Roles I hire for :,"Signal Processing, Machine Learning, Neural Ne..."
30,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Delhi,"Web Technologies, Project Management, Software..."
31,Dhruv Dev Dubey,Company Recruitment Head,Confidential,Bengaluru / Bangalore,"Server Administartion, Verilog, Vhdl, Digital ..."
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Mysoru / Mysore,"Data Analytics, Managed Services, Team Leading..."
33,Avodha,Business Development Associate,Nikitha Palaparthi,Hyderabad / Secunderabad,"Ethical Hacking, Security Operations Center, S..."
34,Priya Khare,Senior Manager,Independent Consultant,Bengaluru / Bangalore,"Data Science, Artificial Intelligence, analyti..."
35,Amit Sharma,Consultant,ASCO consulting,New Delhi,"Machine Learning, Artificial Intelligence, Dat..."
36,Kanan,senior technology instructor,NY INST,Chennai,"C, C++, Artificial Intelligence, Python, Php, ..."
37,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,Aligarh,"Relationship Management, Retail Sales, Private..."
38,Brad,"Manager, Technical Recruiting",O.C. Tanner,Salt Lake City,"Data Science, Software Engineering"
39,Rutuja Pawar,Technical Recruiter,Demand Matrix,Pune,"Data Science, Big Data Analytics, Digital Mark..."
40,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,Bengaluru / Bangalore,"Data Science, Recruitment, Salary"
41,Ankit Sinha,Head Analytics,Suntech Global,Mumbai,"B.Tech, Tableau, Statistics, R, Analytics, Tim..."
42,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,Indore,"Software Development, Business Intelligence, B..."
43,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,Bengaluru / Bangalore,"Data Science, Node.js, Angularjs"
44,Ashwini,Director Global Delivery,MRP Advisers,MYSORE,"Data Science, Media Marketing, Resource Planni..."
45,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,Hyderabad / Secunderabad,"Data Analysis, Learning, Data Science, Compute..."
46,Rajani Nagaraj,HR Manager,WildJasmine,Bengaluru / Bangalore,"Java, Hadoop, R, Machine Learning, Spark, Flum..."
47,ROHIT Kumar,Architect,LNT Private Limited,Mumbai,"Software Development, Core Java, Unit Testing,..."
48,Amir Chowdhury,Managing Partner,Granular.ai,Skills/Roles I hire for :,"Machine Learning, Data Science, Product Manage..."
49,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,Hyderabad / Secunderabad,"Data Science, Machine Learning, Big Data Analy..."

In [112]:
driver.close()

#

 Q8. Scrape the details of Highest selling novels.
URL = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare
You have to find the following details:

 A) Book name

 B) Author name
 
 C) Volumes sold
 
 D) Publisher
 
 E) Genre

In [113]:
driver  =  webdriver.Chrome(r'C:\Users\user\Downloads\chromedriver_win32 (1)\chromedriver.exe')

In [114]:
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare ")

In [115]:
book=[]

book=[i.text for i in driver.find_elements("xpath",'//table[@class="in-article sortable"][1]/tbody/tr/td[2]')]

len(book)

100

In [116]:
book

['Da Vinci Code,The',
 'Harry Potter and the Deathly Hallows',
 "Harry Potter and the Philosopher's Stone",
 'Harry Potter and the Order of the Phoenix',
 'Fifty Shades of Grey',
 'Harry Potter and the Goblet of Fire',
 'Harry Potter and the Chamber of Secrets',
 'Harry Potter and the Prisoner of Azkaban',
 'Angels and Demons',
 "Harry Potter and the Half-blood Prince:Children's Edition",
 'Fifty Shades Darker',
 'Twilight',
 'Girl with the Dragon Tattoo,The:Millennium Trilogy',
 'Fifty Shades Freed',
 'Lost Symbol,The',
 'New Moon',
 'Deception Point',
 'Eclipse',
 'Lovely Bones,The',
 'Curious Incident of the Dog in the Night-time,The',
 'Digital Fortress',
 'Short History of Nearly Everything,A',
 'Girl Who Played with Fire,The:Millennium Trilogy',
 'Breaking Dawn',
 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar',
 'Gruffalo,The',
 "Jamie's 30-Minute Meals",
 'Kite Runner,The',
 'One Day',
 'Thousand Splendid Suns,A',
 "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy",
 "Time Traveler's Wife,The",
 'Atonement',
 "Bridget Jones's Diary:A Novel",
 'World According to Clarkson,The',
 "Captain Corelli's Mandolin",
 'Sound of Laughter,The',
 'Life of Pi',
 'Billy Connolly',
 'Child Called It,A',
 "Gruffalo's Child,The",
 "Angela's Ashes:A Memoir of a Childhood",
 'Birdsong',
 'Northern Lights:His Dark Materials S.',
 'Labyrinth',
 'Harry Potter and the Half-blood Prince',
 'Help,The',
 'Man and Boy',
 'Memoirs of a Geisha',
 "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.",
 'Island,The',
 'PS, I Love You',
 'You are What You Eat:The Plan That Will Change Your Life',
 'Shadow of the Wind,The',
 'Tales of Beedle the Bard,The',
 'Broker,The',
 "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P",
 'Subtle Knife,The:His Dark Materials S.',
 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation',
 "Delia's How to Cook:(Bk.1)",
 'Chocolat',
 'Boy in the Striped Pyjamas,The',
 "My Sister's Keeper",
 'Amber Spyglass,The:His Dark Materials S.',
 'To Kill a Mockingbird',
 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin',
 'Dear Fatty',
 'Short History of Tractors in Ukrainian,A',
 'Hannibal',
 'Lord of the Rings,The',
 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio',
 'Interpretation of Murder,The',
 'Sharon Osbourne Extreme:My Autobiography',
 'Alchemist,The:A Fable About Following Your Dream',
 "At My Mother's Knee ...:and Other Low Joints",
 'Notes from a Small Island',
 'Return of the Naked Chef,The',
 'Bridget Jones: The Edge of Reason',
 "Jamie's Italy",
 'I Can Make You Thin',
 'Down Under',
 'Summons,The',
 'Small Island',
 'Nigella Express',
 'Brick Lane',
 "Memory Keeper's Daughter,The",
 'Room on the Broom',
 'About a Boy',
 'My Booky Wook',
 'God Delusion,The',
 '"Beano" Annual,The',
 'White Teeth',
 'House at Riverton,The',
 'Book Thief,The',
 'Nights of Rain and Stars',
 'Ghost,The',
 'Happy Days with the Naked Chef',
 'Hunger Games,The:Hunger Games Trilogy',
 "Lost Boy,The:A Foster Child's Search for the Love of a Family",
 "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours"]

In [117]:
author=[]

author=[i.text for i in driver.find_elements("xpath",'//table[@class="in-article sortable"][1]/tbody/tr/td[3]')]

len(author)

100

In [118]:
author

['Brown, Dan',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'James, E. L.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Brown, Dan',
 'Rowling, J.K.',
 'James, E. L.',
 'Meyer, Stephenie',
 'Larsson, Stieg',
 'James, E. L.',
 'Brown, Dan',
 'Meyer, Stephenie',
 'Brown, Dan',
 'Meyer, Stephenie',
 'Sebold, Alice',
 'Haddon, Mark',
 'Brown, Dan',
 'Bryson, Bill',
 'Larsson, Stieg',
 'Meyer, Stephenie',
 'Carle, Eric',
 'Donaldson, Julia',
 'Oliver, Jamie',
 'Hosseini, Khaled',
 'Nicholls, David',
 'Hosseini, Khaled',
 'Larsson, Stieg',
 'Niffenegger, Audrey',
 'McEwan, Ian',
 'Fielding, Helen',
 'Clarkson, Jeremy',
 'Bernieres, Louis de',
 'Kay, Peter',
 'Martel, Yann',
 'Stephenson, Pamela',
 'Pelzer, Dave',
 'Donaldson, Julia',
 'McCourt, Frank',
 'Faulks, Sebastian',
 'Pullman, Philip',
 'Mosse, Kate',
 'Rowling, J.K.',
 'Stockett, Kathryn',
 'Parsons, Tony',
 'Golden, Arthur',
 'McCall Smith, Alexander',
 'Hislop, Victoria',
 'Ahern, Cecelia',
 'McKeith, Gillian',
 'Zafon, Carlos Ruiz',
 'Rowling, J.K.',
 'Grisham, John',
 'Atkins, Robert C.',
 'Pullman, Philip',
 'Truss, Lynne',
 'Smith, Delia',
 'Harris, Joanne',
 'Boyne, John',
 'Picoult, Jodi',
 'Pullman, Philip',
 'Lee, Harper',
 'Gray, John',
 'French, Dawn',
 'Lewycka, Marina',
 'Harris, Thomas',
 'Tolkien, J. R. R.',
 'Moore, Michael',
 'Rubenfeld, Jed',
 'Osbourne, Sharon',
 'Coelho, Paulo',
 "O'Grady, Paul",
 'Bryson, Bill',
 'Oliver, Jamie',
 'Fielding, Helen',
 'Oliver, Jamie',
 'McKenna, Paul',
 'Bryson, Bill',
 'Grisham, John',
 'Levy, Andrea',
 'Lawson, Nigella',
 'Ali, Monica',
 'Edwards, Kim',
 'Donaldson, Julia',
 'Hornby, Nick',
 'Brand, Russell',
 'Dawkins, Richard',
 '0',
 'Smith, Zadie',
 'Morton, Kate',
 'Zusak, Markus',
 'Binchy, Maeve',
 'Harris, Robert',
 'Oliver, Jamie',
 'Collins, Suzanne',
 'Pelzer, Dave',
 'Oliver, Jamie']

In [119]:
vol=[]

vol=[i.text for i in driver.find_elements("xpath",'//table[@class="in-article sortable"][1]/tbody/tr/td[4]')]

len(vol)

100

In [120]:
vol

['5,094,805',
 '4,475,152',
 '4,200,654',
 '4,179,479',
 '3,758,936',
 '3,583,215',
 '3,484,047',
 '3,377,906',
 '3,193,946',
 '2,950,264',
 '2,479,784',
 '2,315,405',
 '2,233,570',
 '2,193,928',
 '2,183,031',
 '2,152,737',
 '2,062,145',
 '2,052,876',
 '2,005,598',
 '1,979,552',
 '1,928,900',
 '1,852,919',
 '1,814,784',
 '1,787,118',
 '1,783,535',
 '1,781,269',
 '1,743,266',
 '1,629,119',
 '1,616,068',
 '1,583,992',
 '1,555,135',
 '1,546,886',
 '1,539,428',
 '1,508,205',
 '1,489,403',
 '1,352,318',
 '1,310,207',
 '1,310,176',
 '1,231,957',
 '1,217,712',
 '1,208,711',
 '1,204,058',
 '1,184,967',
 '1,181,503',
 '1,181,093',
 '1,153,181',
 '1,132,336',
 '1,130,802',
 '1,126,337',
 '1,115,549',
 '1,108,328',
 '1,107,379',
 '1,104,403',
 '1,092,349',
 '1,090,847',
 '1,087,262',
 '1,054,196',
 '1,037,160',
 '1,023,688',
 '1,015,956',
 '1,009,873',
 '1,004,414',
 '1,003,780',
 '1,002,314',
 '998,213',
 '992,846',
 '986,753',
 '986,115',
 '970,509',
 '967,466',
 '963,353',
 '962,515',
 '959,496',
 '956,114',
 '945,640',
 '931,312',
 '925,425',
 '924,695',
 '906,968',
 '905,086',
 '890,847',
 '869,671',
 '869,659',
 '862,602',
 '856,540',
 '845,858',
 '842,535',
 '828,215',
 '820,563',
 '816,907',
 '816,585',
 '815,586',
 '814,370',
 '809,641',
 '808,900',
 '807,311',
 '794,201',
 '792,187',
 '791,507',
 '791,095']

In [121]:
pub=[]

pub=[i.text for i in driver.find_elements("xpath",'//table[@class="in-article sortable"][1]/tbody/tr/td[5]')]

len(pub)

100

In [122]:
pub

['Transworld',
 'Bloomsbury',
 'Bloomsbury',
 'Bloomsbury',
 'Random House',
 'Bloomsbury',
 'Bloomsbury',
 'Bloomsbury',
 'Transworld',
 'Bloomsbury',
 'Random House',
 'Little, Brown Book',
 'Quercus',
 'Random House',
 'Transworld',
 'Little, Brown Book',
 'Transworld',
 'Little, Brown Book',
 'Pan Macmillan',
 'Random House',
 'Transworld',
 'Transworld',
 'Quercus',
 'Little, Brown Book',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Bloomsbury',
 'Hodder & Stoughton',
 'Bloomsbury',
 'Quercus',
 'Random House',
 'Random House',
 'Pan Macmillan',
 'Penguin',
 'Random House',
 'Random House',
 'Canongate',
 'HarperCollins',
 'Orion',
 'Pan Macmillan',
 'HarperCollins',
 'Random House',
 'Scholastic Ltd.',
 'Orion',
 'Bloomsbury',
 'Penguin',
 'HarperCollins',
 'Random House',
 'Little, Brown Book',
 'Headline',
 'HarperCollins',
 'Penguin',
 'Orion',
 'Bloomsbury',
 'Random House',
 'Random House',
 'Scholastic Ltd.',
 'Profile Books Group',
 'Random House',
 'Transworld',
 'Random House Childrens Books G',
 'Hodder & Stoughton',
 'Scholastic Ltd.',
 'Random House',
 'HarperCollins',
 'Random House',
 'Penguin',
 'Random House',
 'HarperCollins',
 'Penguin',
 'Headline',
 'Little, Brown Book',
 'HarperCollins',
 'Transworld',
 'Transworld',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Transworld',
 'Transworld',
 'Random House',
 'Headline',
 'Random House',
 'Transworld',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Hodder & Stoughton',
 'Transworld',
 'D.C. Thomson',
 'Penguin',
 'Pan Macmillan',
 'Transworld',
 'Orion',
 'Random House',
 'Penguin',
 'Scholastic Ltd.',
 'Orion',
 'Penguin']

In [123]:
genre=[]

genre=[i.text for i in driver.find_elements("xpath",'//table[@class="in-article sortable"][1]/tbody/tr/td[6]')]

len(genre)

100

In [124]:
genre

['Crime, Thriller & Adventure',
 "Children's Fiction",
 "Children's Fiction",
 "Children's Fiction",
 'Romance & Sagas',
 "Children's Fiction",
 "Children's Fiction",
 "Children's Fiction",
 'Crime, Thriller & Adventure',
 "Children's Fiction",
 'Romance & Sagas',
 'Young Adult Fiction',
 'Crime, Thriller & Adventure',
 'Romance & Sagas',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'Popular Science',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'Picture Books',
 'Picture Books',
 'Food & Drink: General',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Humour: Collections & General',
 'General & Literary Fiction',
 'Autobiography: General',
 'General & Literary Fiction',
 'Biography: The Arts',
 'Autobiography: General',
 'Picture Books',
 'Autobiography: General',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Science Fiction & Fantasy',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Fitness & Diet',
 'General & Literary Fiction',
 "Children's Fiction",
 'Crime, Thriller & Adventure',
 'Fitness & Diet',
 'Young Adult Fiction',
 'Usage & Writing Guides',
 'Food & Drink: General',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Popular Culture & Media: General Interest',
 'Autobiography: The Arts',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'Science Fiction & Fantasy',
 'Current Affairs & Issues',
 'Crime, Thriller & Adventure',
 'Autobiography: The Arts',
 'General & Literary Fiction',
 'Autobiography: The Arts',
 'Travel Writing',
 'Food & Drink: General',
 'General & Literary Fiction',
 'National & Regional Cuisine',
 'Fitness & Diet',
 'Travel Writing',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'Food & Drink: General',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Picture Books',
 'General & Literary Fiction',
 'Autobiography: The Arts',
 'Popular Science',
 "Children's Annuals",
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Food & Drink: General',
 'Young Adult Fiction',
 'Biography: General',
 'Food & Drink: General']

In [125]:
len(book),len(author),len(vol),len(pub),len(genre)

(100, 100, 100, 100, 100)

In [126]:
df=pd.DataFrame({'BOOK NAME':book,'AUTHOR NAME':author,'VOLUMES SOLD':vol,'PUBLISHER':pub,'GENRE':genre})
df

,BOOK NAME,AUTHOR NAME,VOLUMES SOLD,PUBLISHER,GENRE
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [127]:
driver.close()

#

Q9. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:

 A) Name

 B) Year span
 
 C) Genre
 
 D) Run time
 
 E) Ratings
 
 F) Votes

In [128]:
driver  =  webdriver.Chrome(r'C:\Users\user\Downloads\chromedriver_win32 (1)\chromedriver.exe')

In [129]:
driver.get('https://www.imdb.com/list/ls095964455/')

In [130]:
name=[]

name=[i.text for i in driver.find_elements("xpath",'//h3[@class="lister-item-header"]')]

len(name)

100

In [131]:
name

['1. Game of Thrones (2011–2019)',
 '2. Stranger Things (2016– )',
 '3. The Walking Dead (2010–2022)',
 '4. 13 Reasons Why (2017–2020)',
 '5. The 100 (2014–2020)',
 '6. Orange Is the New Black (2013–2019)',
 '7. Riverdale (2017– )',
 "8. Grey's Anatomy (2005– )",
 '9. The Flash (2014–2023)',
 '10. Arrow (2012–2020)',
 '11. Money Heist (2017–2021)',
 '12. The Big Bang Theory (2007–2019)',
 '13. Black Mirror (2011–2019)',
 '14. Sherlock (2010–2017)',
 '15. Vikings (2013–2020)',
 '16. Pretty Little Liars (2010–2017)',
 '17. The Vampire Diaries (2009–2017)',
 '18. American Horror Story (2011– )',
 '19. Breaking Bad (2008–2013)',
 '20. Lucifer (2016–2021)',
 '21. Supernatural (2005–2020)',
 '22. Prison Break (2005–2017)',
 '23. How to Get Away with Murder (2014–2020)',
 '24. Teen Wolf (2011–2017)',
 '25. The Simpsons (1989– )',
 '26. Once Upon a Time (2011–2018)',
 '27. Narcos (2015–2017)',
 '28. Daredevil (2015–2018)',
 '29. Friends (1994–2004)',
 '30. How I Met Your Mother (2005–2014)',
 '31. Suits (2011–2019)',
 '32. Mr. Robot (2015–2019)',
 '33. The Originals (2013–2018)',
 '34. Supergirl (2015–2021)',
 '35. Gossip Girl (2007–2012)',
 '36. Sense8 (2015–2018)',
 '37. Gotham (2014–2019)',
 '38. Westworld (2016– )',
 '39. Jessica Jones (2015–2019)',
 '40. Modern Family (2009– )',
 '41. Rick and Morty (2013– )',
 '42. Shadowhunters (2016–2019)',
 '43. The End of the F***ing World (2017–2019)',
 '44. House of Cards (2013–2018)',
 '45. Dark (2017–2020)',
 '46. Elite (2018– )',
 '47. Sex Education (2019– )',
 '48. Shameless (2011–2021)',
 '49. New Girl (2011–2018)',
 '50. Agents of S.H.I.E.L.D. (2013–2020)',
 '51. You (2018– )',
 '52. Dexter (2006–2013)',
 '53. Fear the Walking Dead (2015– )',
 '54. Family Guy (1999– )',
 '55. The Blacklist (2013– )',
 '56. Lost (2004–2010)',
 '57. Peaky Blinders (2013–2022)',
 '58. House (2004–2012)',
 '59. Quantico (2015–2018)',
 '60. Orphan Black (2013–2017)',
 '61. Homeland (2011–2020)',
 '62. Blindspot (2015–2020)',
 "63. DC's Legends of Tomorrow (2016–2022)",
 "64. The Handmaid's Tale (2017– )",
 '65. Chilling Adventures of Sabrina (2018–2020)',
 '66. The Good Doctor (2017– )',
 '67. Jane the Virgin (2014–2019)',
 '68. Glee (2009–2015)',
 '69. South Park (1997– )',
 '70. Brooklyn Nine-Nine (2013–2021)',
 '71. Under the Dome (2013–2015)',
 '72. The Umbrella Academy (2019–2022)',
 '73. True Detective (2014–2019)',
 '74. The OA (2016–2019)',
 '75. Desperate Housewives (2004–2012)',
 '76. Better Call Saul (2015–2022)',
 '77. Bates Motel (2013–2017)',
 '78. The Punisher (2017–2019)',
 '79. Atypical (2017–2021)',
 '80. Dynasty (2017–2022)',
 '81. This Is Us (2016–2022)',
 '82. The Good Place (2016–2020)',
 '83. Iron Fist (2017–2018)',
 '84. The Rain (2018–2020)',
 '85. Mindhunter (2017–2019)',
 '86. Revenge (2011–2015)',
 '87. Luke Cage (2016–2018)',
 '88. Scandal (2012–2018)',
 '89. The Defenders (2017)',
 '90. Big Little Lies (2017–2019)',
 '91. Insatiable (2018–2019)',
 '92. The Mentalist (2008–2015)',
 '93. The Crown (2016– )',
 '94. Chernobyl (2019)',
 '95. iZombie (2015–2019)',
 '96. Reign (2013–2017)',
 '97. A Series of Unfortunate Events (2017–2019)',
 '98. Criminal Minds (2005–2020)',
 '99. Scream: The TV Series (2015–2019)',
 '100. The Haunting of Hill House (2018)']

In [132]:
year_span=[]
year=driver.find_elements("xpath",'//span[@class="lister-item-year text-muted unbold"]')
for i in year:
    year_span.append(i.text)
len(year_span)

100

In [133]:
year_span

['(2011–2019)',
 '(2016– )',
 '(2010–2022)',
 '(2017–2020)',
 '(2014–2020)',
 '(2013–2019)',
 '(2017– )',
 '(2005– )',
 '(2014–2023)',
 '(2012–2020)',
 '(2017–2021)',
 '(2007–2019)',
 '(2011–2019)',
 '(2010–2017)',
 '(2013–2020)',
 '(2010–2017)',
 '(2009–2017)',
 '(2011– )',
 '(2008–2013)',
 '(2016–2021)',
 '(2005–2020)',
 '(2005–2017)',
 '(2014–2020)',
 '(2011–2017)',
 '(1989– )',
 '(2011–2018)',
 '(2015–2017)',
 '(2015–2018)',
 '(1994–2004)',
 '(2005–2014)',
 '(2011–2019)',
 '(2015–2019)',
 '(2013–2018)',
 '(2015–2021)',
 '(2007–2012)',
 '(2015–2018)',
 '(2014–2019)',
 '(2016– )',
 '(2015–2019)',
 '(2009– )',
 '(2013– )',
 '(2016–2019)',
 '(2017–2019)',
 '(2013–2018)',
 '(2017–2020)',
 '(2018– )',
 '(2019– )',
 '(2011–2021)',
 '(2011–2018)',
 '(2013–2020)',
 '(2018– )',
 '(2006–2013)',
 '(2015– )',
 '(1999– )',
 '(2013– )',
 '(2004–2010)',
 '(2013–2022)',
 '(2004–2012)',
 '(2015–2018)',
 '(2013–2017)',
 '(2011–2020)',
 '(2015–2020)',
 '(2016–2022)',
 '(2017– )',
 '(2018–2020)',
 '(2017– )',
 '(2014–2019)',
 '(2009–2015)',
 '(1997– )',
 '(2013–2021)',
 '(2013–2015)',
 '(2019–2022)',
 '(2014–2019)',
 '(2016–2019)',
 '(2004–2012)',
 '(2015–2022)',
 '(2013–2017)',
 '(2017–2019)',
 '(2017–2021)',
 '(2017–2022)',
 '(2016–2022)',
 '(2016–2020)',
 '(2017–2018)',
 '(2018–2020)',
 '(2017–2019)',
 '(2011–2015)',
 '(2016–2018)',
 '(2012–2018)',
 '(2017)',
 '(2017–2019)',
 '(2018–2019)',
 '(2008–2015)',
 '(2016– )',
 '(2019)',
 '(2015–2019)',
 '(2013–2017)',
 '(2017–2019)',
 '(2005–2020)',
 '(2015–2019)',
 '(2018)']

In [134]:
genre=[]
gen=driver.find_elements("xpath",'//span[@class="genre"]')
for i in gen:
    genre.append(i.text)
len(genre)

100

In [135]:
genre

['Action, Adventure, Drama',
 'Drama, Fantasy, Horror',
 'Drama, Horror, Thriller',
 'Drama, Mystery, Thriller',
 'Drama, Mystery, Sci-Fi',
 'Comedy, Crime, Drama',
 'Crime, Drama, Mystery',
 'Drama, Romance',
 'Action, Adventure, Drama',
 'Action, Adventure, Crime',
 'Action, Crime, Drama',
 'Comedy, Romance',
 'Drama, Mystery, Sci-Fi',
 'Crime, Drama, Mystery',
 'Action, Adventure, Drama',
 'Drama, Mystery, Romance',
 'Drama, Fantasy, Horror',
 'Drama, Horror, Sci-Fi',
 'Crime, Drama, Thriller',
 'Crime, Drama, Fantasy',
 'Drama, Fantasy, Horror',
 'Action, Crime, Drama',
 'Crime, Drama, Mystery',
 'Action, Drama, Fantasy',
 'Animation, Comedy',
 'Adventure, Fantasy, Romance',
 'Biography, Crime, Drama',
 'Action, Crime, Drama',
 'Comedy, Romance',
 'Comedy, Romance',
 'Comedy, Drama',
 'Crime, Drama, Thriller',
 'Drama, Fantasy, Horror',
 'Action, Adventure, Drama',
 'Drama, Romance',
 'Drama, Mystery, Sci-Fi',
 'Action, Crime, Drama',
 'Drama, Mystery, Sci-Fi',
 'Action, Crime, Drama',
 'Comedy, Drama, Romance',
 'Animation, Adventure, Comedy',
 'Action, Drama, Fantasy',
 'Adventure, Comedy, Crime',
 'Drama',
 'Crime, Drama, Mystery',
 'Crime, Drama, Thriller',
 'Comedy, Drama',
 'Comedy, Drama',
 'Comedy, Romance',
 'Action, Adventure, Drama',
 'Crime, Drama, Romance',
 'Crime, Drama, Mystery',
 'Drama, Horror, Sci-Fi',
 'Animation, Comedy',
 'Crime, Drama, Mystery',
 'Adventure, Drama, Fantasy',
 'Crime, Drama',
 'Drama, Mystery',
 'Crime, Drama, Mystery',
 'Drama, Sci-Fi, Thriller',
 'Crime, Drama, Mystery',
 'Action, Crime, Drama',
 'Action, Adventure, Drama',
 'Drama, Thriller',
 'Drama, Fantasy, Horror',
 'Drama',
 'Comedy',
 'Comedy, Drama, Music',
 'Animation, Comedy',
 'Comedy, Crime',
 'Drama, Mystery, Sci-Fi',
 'Action, Adventure, Comedy',
 'Crime, Drama, Mystery',
 'Drama, Fantasy, Mystery',
 'Comedy, Drama, Mystery',
 'Crime, Drama',
 'Drama, Horror, Mystery',
 'Action, Crime, Drama',
 'Comedy, Drama',
 'Drama',
 'Comedy, Drama, Romance',
 'Comedy, Drama, Fantasy',
 'Action, Adventure, Crime',
 'Drama, Sci-Fi, Thriller',
 'Crime, Drama, Mystery',
 'Drama, Mystery, Thriller',
 'Action, Crime, Drama',
 'Drama, Thriller',
 'Action, Adventure, Crime',
 'Crime, Drama, Mystery',
 'Comedy, Drama, Thriller',
 'Crime, Drama, Mystery',
 'Biography, Drama, History',
 'Drama, History, Thriller',
 'Comedy, Crime, Drama',
 'Drama',
 'Adventure, Comedy, Drama',
 'Crime, Drama, Mystery',
 'Comedy, Crime, Drama',
 'Drama, Horror, Mystery']

In [136]:
runtime=[]
run_tm=driver.find_elements("xpath",'//span[@class="runtime"]')
for i in run_tm:
    runtime.append(i.text)
len(runtime)

100

In [137]:
runtime

['57 min',
 '51 min',
 '44 min',
 '60 min',
 '43 min',
 '59 min',
 '45 min',
 '41 min',
 '43 min',
 '42 min',
 '70 min',
 '22 min',
 '60 min',
 '88 min',
 '44 min',
 '44 min',
 '43 min',
 '60 min',
 '49 min',
 '42 min',
 '44 min',
 '44 min',
 '43 min',
 '41 min',
 '22 min',
 '60 min',
 '49 min',
 '54 min',
 '22 min',
 '22 min',
 '44 min',
 '49 min',
 '45 min',
 '43 min',
 '42 min',
 '60 min',
 '42 min',
 '62 min',
 '56 min',
 '22 min',
 '23 min',
 '42 min',
 '25 min',
 '51 min',
 '60 min',
 '60 min',
 '45 min',
 '46 min',
 '22 min',
 '45 min',
 '45 min',
 '53 min',
 '44 min',
 '22 min',
 '43 min',
 '44 min',
 '60 min',
 '44 min',
 '42 min',
 '44 min',
 '55 min',
 '42 min',
 '42 min',
 '60 min',
 '60 min',
 '41 min',
 '60 min',
 '44 min',
 '22 min',
 '22 min',
 '43 min',
 '60 min',
 '55 min',
 '60 min',
 '45 min',
 '46 min',
 '45 min',
 '53 min',
 '30 min',
 '42 min',
 '45 min',
 '22 min',
 '55 min',
 '45 min',
 '60 min',
 '44 min',
 '55 min',
 '43 min',
 '50 min',
 '60 min',
 '45 min',
 '43 min',
 '58 min',
 '330 min',
 '42 min',
 '42 min',
 '50 min',
 '42 min',
 '45 min',
 '572 min']

In [138]:
rating=[]
ratings=driver.find_elements("xpath",'//div[@class="lister-item-content"]')
for i in ratings:
    rating.append(i.text.split('\n')[2])
len(rating)

100

In [139]:
rating

['9.2',
 '8.7',
 '8.2',
 '7.5',
 '7.6',
 '8.1',
 '6.6',
 '7.6',
 '7.6',
 '7.5',
 '8.2',
 '8.2',
 '8.8',
 '9.1',
 '8.5',
 '7.4',
 '7.7',
 '8',
 '9.5',
 '8.1',
 '8.4',
 '8.3',
 '8.1',
 '7.7',
 '8.7',
 '7.7',
 '8.8',
 '8.6',
 '8.9',
 '8.3',
 '8.5',
 '8.6',
 '8.3',
 '6.2',
 '7.4',
 '8.2',
 '7.8',
 '8.6',
 '7.9',
 '8.5',
 '9.2',
 '6.5',
 '8.1',
 '8.7',
 '8.7',
 '7.4',
 '8.4',
 '8.6',
 '7.7',
 '7.5',
 '7.7',
 '8.7',
 '6.8',
 '8.2',
 '8',
 '8.3',
 '8.8',
 '8.7',
 '6.6',
 '8.3',
 '8.3',
 '7.3',
 '6.7',
 '8.4',
 '7.4',
 '8.1',
 '7.9',
 '6.8',
 '8.7',
 '8.4',
 '6.5',
 '7.9',
 '8.9',
 '7.8',
 '7.6',
 '8.9',
 '8.1',
 '8.5',
 '8.3',
 '7.2',
 '8.7',
 '8.2',
 '6.4',
 '6.3',
 '8.6',
 '7.8',
 '7.3',
 '7.7',
 '7.2',
 '8.5',
 '6.5',
 '8.1',
 '8.7',
 '9.4',
 '7.8',
 '7.4',
 '7.8',
 '8.1',
 '7.1',
 '8.6']

In [140]:
votes=[]
vote=driver.find_elements("xpath",'//div[@class="lister-item-content"]')
for i in vote:
    votes.append(i.text.split('\n')[6])
len(votes)

100

In [141]:
votes

['Votes: 2,020,901',
 'Votes: 1,117,011',
 'Votes: 959,586',
 'Votes: 286,875',
 'Votes: 246,474',
 'Votes: 298,590',
 'Votes: 141,986',
 'Votes: 300,399',
 'Votes: 342,261',
 'Votes: 428,354',
 'Votes: 464,933',
 'Votes: 792,397',
 'Votes: 528,642',
 'Votes: 905,626',
 'Votes: 517,762',
 'Votes: 165,283',
 'Votes: 315,326',
 'Votes: 310,526',
 'Votes: 1,788,912',
 'Votes: 314,457',
 'Votes: 435,459',
 'Votes: 524,508',
 'Votes: 149,058',
 'Votes: 145,456',
 'Votes: 400,181',
 'Votes: 222,370',
 'Votes: 411,845',
 'Votes: 428,032',
 'Votes: 968,822',
 'Votes: 671,146',
 'Votes: 402,162',
 'Votes: 379,870',
 'Votes: 133,792',
 'Votes: 123,103',
 'Votes: 171,941',
 'Votes: 153,128',
 'Votes: 228,139',
 'Votes: 489,411',
 'Votes: 211,605',
 'Votes: 418,654',
 'Votes: 489,302',
 'Votes: 62,370',
 'Votes: 183,182',
 'Votes: 498,449',
 'Votes: 365,423',
 'Votes: 75,805',
 'Votes: 268,473',
 'Votes: 235,657',
 'Votes: 219,740',
 'Votes: 215,443',
 'Votes: 231,147',
 'Votes: 717,524',
 'Votes: 128,549',
 'Votes: 332,185',
 'Votes: 243,390',
 'Votes: 543,729',
 'Votes: 516,561',
 'Votes: 454,621',
 'Votes: 60,723',
 'Votes: 109,787',
 'Votes: 337,940',
 'Votes: 73,245',
 'Votes: 103,856',
 'Votes: 221,800',
 'Votes: 92,385',
 'Votes: 91,531',
 'Votes: 49,213',
 'Votes: 147,192',
 'Votes: 363,939',
 'Votes: 302,610',
 'Votes: 106,112',
 'Votes: 234,886',
 'Votes: 556,582',
 'Votes: 103,451',
 'Votes: 127,378',
 'Votes: 450,566',
 'Votes: 106,515',
 'Votes: 226,994',
 'Votes: 85,814',
 'Votes: 21,745',
 'Votes: 140,329',
 'Votes: 153,837',
 'Votes: 128,953',
 'Votes: 36,563',
 'Votes: 276,849',
 'Votes: 119,540',
 'Votes: 129,283',
 'Votes: 73,207',
 'Votes: 105,447',
 'Votes: 193,249',
 'Votes: 28,175',
 'Votes: 182,368',
 'Votes: 195,066',
 'Votes: 721,121',
 'Votes: 67,366',
 'Votes: 49,263',
 'Votes: 60,145',
 'Votes: 193,388',
 'Votes: 40,802',
 'Votes: 233,278']

In [142]:
df=pd.DataFrame({'NAME':name,'YEAR SPAN':year_span,'GENRE':genre,'RUN TIME':runtime,'RATINGS':rating,'VOTES':votes})
df

,NAME,YEAR SPAN,GENRE,RUN TIME,RATINGS,VOTES
0,1. Game of Thrones (2011–2019),(2011–2019),"Action, Adventure, Drama",57 min,9.2,"Votes: 2,020,901"
1,2. Stranger Things (2016– ),(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"Votes: 1,117,011"
2,3. The Walking Dead (2010–2022),(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"Votes: 959,586"
3,4. 13 Reasons Why (2017–2020),(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"Votes: 286,875"
4,5. The 100 (2014–2020),(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"Votes: 246,474"
...,...,...,...,...,...,...
95,96. Reign (2013–2017),(2013–2017),Drama,42 min,7.4,"Votes: 49,263"
96,97. A Series of Unfortunate Events (2017–2019),(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"Votes: 60,145"
97,98. Criminal Minds (2005–2020),(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"Votes: 193,388"
98,99. Scream: The TV Series (2015–2019),(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"Votes: 40,802"
99,100. The Haunting of Hill House (2018),(2018),"Drama, Horror, Mystery",572 min,8.6,"Votes: 233,278"

In [143]:
driver.close()

#

Q10. Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/
You have to find the following details: 

 A) Dataset name
 
 B) Data type
 
 C) Task
 
 D) Attribute type
 
 E) No of instances
 
 F) No of attribute
 
 G) Year

Note: - from the home page you have to go to the ShowAllDataset page through code.

In [144]:
driver  =  webdriver.Chrome(r'C:\Users\user\Downloads\chromedriver_win32 (1)\chromedriver.exe')

In [145]:
driver.get('https://archive.ics.uci.edu/')

In [146]:
show_datasets=driver.find_element("xpath",'/html/body/table[1]/tbody/tr/td[2]/span[2]/a/font/b')
show_datasets.click()

In [159]:
name=[]
data=driver.find_elements("xpath",'//table[@border="1"][1]/tbody/tr/td[1]')
for i in data:
    name.append(i.text)
len(name)

623

In [160]:
name

['Name',
 '  Abalone',
 '  Adult',
 '  Annealing',
 '  Anonymous Microsoft Web Data',
 '  Arrhythmia',
 '  Artificial Characters',
 '  Audiology (Original)',
 '  Audiology (Standardized)',
 '  Auto MPG',
 '  Automobile',
 '  Badges',
 '  Balance Scale',
 '  Balloons',
 '  Breast Cancer',
 '  Breast Cancer Wisconsin (Original)',
 '  Breast Cancer Wisconsin (Prognostic)',
 '  Breast Cancer Wisconsin (Diagnostic)',
 '  Pittsburgh Bridges',
 '  Car Evaluation',
 '  Census Income',
 '  Chess (King-Rook vs. King-Knight)',
 '  Chess (King-Rook vs. King-Pawn)',
 '  Chess (King-Rook vs. King)',
 '  Chess (Domain Theories)',
 '  Bach Chorales',
 '  Connect-4',
 '  Credit Approval',
 '  Japanese Credit Screening',
 '  Computer Hardware',
 '  Contraceptive Method Choice',
 '  Covertype',
 '  Cylinder Bands',
 '  Dermatology',
 '  Diabetes',
 '  DGP2 - The Second Data Generation Program',
 '  Document Understanding',
 '  EBL Domain Theories',
 '  Echocardiogram',
 '  Ecoli',
 '  Flags',
 '  Function Finding',
 '  Glass Identification',
 "  Haberman's Survival",
 '  Hayes-Roth',
 '  Heart Disease',
 '  Hepatitis',
 '  Horse Colic',
 '  ICU',
 '  Image Segmentation',
 '  Internet Advertisements',
 '  Ionosphere',
 '  Iris',
 '  ISOLET',
 '  Kinship',
 '  Labor Relations',
 '  LED Display Domain',
 '  Lenses',
 '  Letter Recognition',
 '  Liver Disorders',
 '  Logic Theorist',
 '  Lung Cancer',
 '  Lymphography',
 '  Mechanical Analysis',
 '  Meta-data',
 '  Mobile Robots',
 '  Molecular Biology (Promoter Gene Sequences)',
 '  Molecular Biology (Protein Secondary Structure)',
 '  Molecular Biology (Splice-junction Gene Sequences)',
 "  MONK's Problems",
 '  Moral Reasoner',
 '  Multiple Features',
 '  Mushroom',
 '  Musk (Version 1)',
 '  Musk (Version 2)',
 '  Nursery',
 '  Othello Domain Theory',
 '  Page Blocks Classification',
 '  Optical Recognition of Handwritten Digits',
 '  Pen-Based Recognition of Handwritten Digits',
 '  Post-Operative Patient',
 '  Primary Tumor',
 '  Prodigy',
 '  Qualitative Structure Activity Relationships',
 '  Quadruped Mammals',
 '  Servo',
 '  Shuttle Landing Control',
 '  Solar Flare',
 '  Soybean (Large)',
 '  Soybean (Small)',
 '  Challenger USA Space Shuttle O-Ring',
 '  Low Resolution Spectrometer',
 '  Spambase',
 '  SPECT Heart',
 '  SPECTF Heart',
 '  Sponge',
 '  Statlog Project',
 '  Student Loan Relational',
 '  Teaching Assistant Evaluation',
 '  Tic-Tac-Toe Endgame',
 '  Thyroid Disease',
 '  Trains',
 '  University',
 '  Congressional Voting Records',
 '  Water Treatment Plant',
 '  Waveform Database Generator (Version 1)',
 '  Waveform Database Generator (Version 2)',
 '  Wine',
 '  Yeast',
 '  Zoo',
 '  Undocumented',
 '  Twenty Newsgroups',
 '  Australian Sign Language signs',
 '  Australian Sign Language signs (High Quality)',
 '  US Census Data (1990)',
 '  Census-Income (KDD)',
 '  Coil 1999 Competition Data',
 '  Corel Image Features',
 '  E. Coli Genes',
 '  EEG Database',
 '  El Nino',
 '  Entree Chicago Recommendation Data',
 '  CMU Face Images',
 '  Insurance Company Benchmark (COIL 2000)',
 '  Internet Usage Data',
 '  IPUMS Census Database',
 '  Japanese Vowels',
 '  KDD Cup 1998 Data',
 '  KDD Cup 1999 Data',
 '  M. Tuberculosis Genes',
 '  Movie',
 '  MSNBC.com Anonymous Web Data',
 '  NSF Research Award Abstracts 1990-2003',
 '  Pioneer-1 Mobile Robot Data',
 '  Pseudo Periodic Synthetic Time Series',
 '  Reuters-21578 Text Categorization Collection',
 '  Robot Execution Failures',
 '  Synthetic Control Chart Time Series',
 '  Syskill and Webert Web Page Ratings',
 '  UNIX User Data',
 '  Volcanoes on Venus - JARtool experiment',
 '  Statlog (Australian Credit Approval)',
 '  Statlog (German Credit Data)',
 '  Statlog (Heart)',
 '  Statlog (Landsat Satellite)',
 '  Statlog (Image Segmentation)',
 '  Statlog (Shuttle)',
 '  Statlog (Vehicle Silhouettes)',
 '  Connectionist Bench (Nettalk Corpus)',
 '  Connectionist Bench (Sonar, Mines vs. Rocks)',
 '  Connectionist Bench (Vowel Recognition - Deterding Data)',
 '  Economic Sanctions',
 '  Protein Data',
 '  Cloud',
 '  CalIt2 Building People Counts',
 '  Dodgers Loop Sensor',
 '  Poker Hand',
 '  MAGIC Gamma Telescope',
 '  UJI Pen Characters',
 '  Mammographic Mass',
 '  Forest Fires',
 '  Reuters Transcribed Subset',
 '  Bag of Words',
 '  Concrete Compressive Strength',
 '  Hill-Valley',
 '  Arcene',
 '  Dexter',
 '  Dorothea',
 '  Gisette',
 '  Madelon',
 '  Ozone Level Detection',
 '  Abscisic Acid Signaling Network',
 '  Parkinsons',
 '  Character Trajectories',
 '  Blood Transfusion Service Center',
 '  UJI Pen Characters (Version 2)',
 '  Semeion Handwritten Digit',
 '  SECOM',
 '  Plants',
 '  Libras Movement',
 '  Concrete Slump Test',
 '  Communities and Crime',
 '  Acute Inflammations',
 '  Wine Quality',
 '  URL Reputation',
 '  p53 Mutants',
 '  Parkinsons Telemonitoring',
 '  Demospongiae',
 '  Opinosis Opinion ⁄ Review',
 '  Breast Tissue',
 '  Cardiotocography',
 '  Wall-Following Robot Navigation Data',
 '  Spoken Arabic Digit',
 '  Localization Data for Person Activity',
 '  AutoUniv',
 '  Steel Plates Faults',
 '  MiniBooNE particle identification',
 '  YearPredictionMSD',
 '  PEMS-SF',
 '  OpinRank Review Dataset',
 '  Relative location of CT slices on axial axis',
 '  Online Handwritten Assamese Characters Dataset',
 '  PubChem Bioassay Data',
 '  Record Linkage Comparison Patterns',
 '  Communities and Crime Unnormalized',
 '  Vertebral Column',
 '  EMG Physical Action Data Set',
 '  Vicon Physical Action Data Set',
 '  Amazon Commerce reviews set',
 '  Amazon Access Samples',
 '  Reuter_50_50',
 '  Farm Ads',
 '  DBWorld e-mails',
 '  KEGG Metabolic Relation Network (Directed)',
 '  KEGG Metabolic Reaction Network (Undirected)',
 '  Bank Marketing',
 '  YouTube Comedy Slam Preference Data',
 '  Gas Sensor Array Drift Dataset',
 '  ILPD (Indian Liver Patient Dataset)',
 '  OPPORTUNITY Activity Recognition',
 '  Nomao',
 '  SMS Spam Collection',
 '  Skin Segmentation',
 '  Planning Relax',
 '  PAMAP2 Physical Activity Monitoring',
 '  Restaurant & consumer data',
 '  CNAE-9',
 '  Individual household electric power consumption',
 '  seeds',
 '  Northix',
 '  QtyT40I10D100K',
 '  Legal Case Reports',
 '  Human Activity Recognition Using Smartphones',
 '  One-hundred plant species leaves data set',
 '  Energy efficiency',
 '  Yacht Hydrodynamics',
 '  Fertility',
 '  Daphnet Freezing of Gait',
 '  3D Road Network (North Jutland, Denmark)',
 '  ISTANBUL STOCK EXCHANGE',
 '  Buzz in social media',
 '  First-order theorem proving',
 '  Wearable Computing: Classification of Body Postures and Movements (PUC-Rio)',
 '  Gas sensor arrays in open sampling settings',
 '  Climate Model Simulation Crashes',
 '  MicroMass',
 '  QSAR biodegradation',
 '  BLOGGER',
 '  Daily and Sports Activities',
 '  User Knowledge Modeling',
 '  Reuters RCV1 RCV2 Multilingual, Multiview Text Categorization Test collection',
 '  NYSK',
 '  Turkiye Student Evaluation',
 "  ser Knowledge Modeling Data (Students' Knowledge Levels on DC Electrical Machines)",
 '  EEG Eye State',
 '  Physicochemical Properties of Protein Tertiary Structure',
 '  seismic-bumps',
 '  banknote authentication',
 '  USPTO Algorithm Challenge, run by NASA-Harvard Tournament Lab and TopCoder Problem: Pat',
 '  YouTube Multiview Video Games Dataset',
 '  Gas Sensor Array Drift Dataset at Different Concentrations',
 '  Activities of Daily Living (ADLs) Recognition Using Binary Sensors',
 '  SkillCraft1 Master Table Dataset',
 '  Weight Lifting Exercises monitored with Inertial Measurement Units',
 '  SML2010',
 '  Bike Sharing Dataset',
 '  Predict keywords activities in a online social media',
 '  Thoracic Surgery Data',
 '  EMG dataset in Lower Limb',
 '  SUSY',
 '  HIGGS',
 '  Qualitative_Bankruptcy',
 '  LSVT Voice Rehabilitation',
 '  Dataset for ADL Recognition with Wrist-worn Accelerometer',
 '  Wilt',
 '  User Identification From Walking Activity',
 '  Activity Recognition from Single Chest-Mounted Accelerometer',
 '  Leaf',
 '  Dresses_Attribute_Sales',
 '  Tamilnadu Electricity Board Hourly Readings',
 '  Airfoil Self-Noise',
 '  Wholesale customers',
 '  Twitter Data set for Arabic Sentiment Analysis',
 '  Combined Cycle Power Plant',
 '  Urban Land Cover',
 '  Diabetes 130-US hospitals for years 1999-2008',
 '  Bach Choral Harmony',
 '  StoneFlakes',
 '  Tennis Major Tournament Match Statistics',
 '  Parkinson Speech Dataset with Multiple Types of Sound Recordings',
 '  Gesture Phase Segmentation',
 '  Perfume Data',
 '  BlogFeedback',
 '  REALDISP Activity Recognition Dataset',
 '  Newspaper and magazine images segmentation dataset',
 '  AAAI 2014 Accepted Papers',
 '  Gas sensor array under flow modulation',
 '  Gas sensor array exposed to turbulent gas mixtures',
 '  UJIIndoorLoc',
 '  Sentence Classification',
 '  Dow Jones Index',
 '  sEMG for Basic Hand movements',
 '  AAAI 2013 Accepted Papers',
 '  Geographical Original of Music',
 '  Condition Based Maintenance of Naval Propulsion Plants',
 '  Grammatical Facial Expressions',
 '  NoisyOffice',
 '  MHEALTH Dataset',
 '  Student Performance',
 '  ElectricityLoadDiagrams20112014',
 '  Gas sensor array under dynamic gas mixtures',
 '  microblogPCU',
 '  Firm-Teacher_Clave-Direction_Classification',
 '  Dataset for Sensorless Drive Diagnosis',
 '  TV News Channel Commercial Detection Dataset',
 '  Phishing Websites',
 '  Greenhouse Gas Observing Network',
 '  Diabetic Retinopathy Debrecen Data Set',
 '  HIV-1 protease cleavage',
 '  Sentiment Labelled Sentences',
 '  Online News Popularity',
 '  Forest type mapping',
 '  wiki4HE',
 '  Online Video Characteristics and Transcoding Time Dataset',
 '  Chronic_Kidney_Disease',
 '  Machine Learning based ZZAlpha Ltd. Stock Recommendations 2012-2014',
 '  Folio',
 '  Taxi Service Trajectory - Prediction Challenge, ECML PKDD 2015',
 '  Cuff-Less Blood Pressure Estimation',
 '  Smartphone-Based Recognition of Human Activities and Postural Transitions',
 '  Mice Protein Expression',
 '  UJIIndoorLoc-Mag',
 '  Heterogeneity Activity Recognition',
 '  Educational Process Mining (EPM): A Learning Analytics Data Set',
 '  HEPMASS',
 '  Indoor User Movement Prediction from RSS data',
 '  Open University Learning Analytics dataset',
 '  default of credit card clients',
 '  Mesothelioma’s disease data set',
 '  Online Retail',
 '  SIFT10M',
 '  GPS Trajectories',
 '  Detect Malacious Executable(AntiVirus)',
 '  Occupancy Detection',
 '  Improved Spiral Test Using Digitized Graphics Tablet for Monitoring Parkinson’s Disease',
 '  News Aggregator',
 '  Air Quality',
 '  Twin gas sensor arrays',
 '  Gas sensors for home activity monitoring',
 '  Facebook Comment Volume Dataset',
 '  Smartphone Dataset for Human Activity Recognition (HAR) in Ambient Assisted Living (AAL)',
 '  Polish companies bankruptcy data',
 '  Activity Recognition system based on Multisensor data fusion (AReM)',
 '  Dota2 Games Results',
 '  Facebook metrics',
 '  UbiqLog (smartphone lifelogging)',
 '  NIPS Conference Papers 1987-2015',
 '  HTRU2',
 '  Drug consumption (quantified)',
 '  Appliances energy prediction',
 '  Miskolc IIS Hybrid IPS',
 '  KDC-4007 dataset Collection',
 '  Geo-Magnetic field and WLAN dataset for indoor localisation from wristband and smartphone',
 '  DrivFace',
 '  Website Phishing',
 '  YouTube Spam Collection',
 '  Beijing PM2.5 Data',
 '  Cargo 2000 Freight Tracking and Tracing',
 '  Cervical cancer (Risk Factors)',
 '  Quality Assessment of Digital Colposcopies',
 '  KASANDR',
 '  FMA: A Dataset For Music Analysis',
 '  Air quality',
 '  Epileptic Seizure Recognition',
 '  Devanagari Handwritten Character Dataset',
 '  Stock portfolio performance',
 '  MoCap Hand Postures',
 '  Early biomarkers of Parkinson�s disease based on natural connected speech',
 '  Data for Software Engineering Teamwork Assessment in Education Setting',
 '  PM2.5 Data of Five Chinese Cities',
 '  Parkinson Disease Spiral Drawings Using Digitized Graphics Tablet',
 '  Sales_Transactions_Dataset_Weekly',
 '  Las Vegas Strip',
 '  Eco-hotel',
 '  MEU-Mobile KSD',
 '  Crowdsourced Mapping',
 '  gene expression cancer RNA-Seq',
 '  Hybrid Indoor Positioning Dataset from WiFi RSSI, Bluetooth and magnetometer',
 '  chestnut – LARVIC',
 '  Burst Header Packet (BHP) flooding attack on Optical Burst Switching (OBS) Network',
 '  Motion Capture Hand Postures',
 '  Anuran Calls (MFCCs)',
 '  TTC-3600: Benchmark dataset for Turkish text categorization',
 '  Gastrointestinal Lesions in Regular Colonoscopy',
 '  Daily Demand Forecasting Orders',
 '  Paper Reviews',
 '  extention of Z-Alizadeh sani dataset',
 '  Z-Alizadeh Sani',
 '  Dynamic Features of VirusShare Executables',
 '  IDA2016Challenge',
 '  DSRC Vehicle Communications',
 '  Mturk User-Perceived Clusters over Images',
 '  Character Font Images',
 '  DeliciousMIL: A Data Set for Multi-Label Multi-Instance Learning with Instance Labels',
 '  Autistic Spectrum Disorder Screening Data for Children',
 '  Autistic Spectrum Disorder Screening Data for Adolescent',
 '  APS Failure at Scania Trucks',
 '  Wireless Indoor Localization',
 '  HCC Survival',
 '  CSM (Conventional and Social Media Movies) Dataset 2014 and 2015',
 '  University of Tehran Question Dataset 2016 (UTQD.2016)',
 '  Autism Screening Adult',
 '  Activity recognition with healthy older people using a batteryless wearable sensor',
 '  Immunotherapy Dataset',
 '  Cryotherapy Dataset',
 '  OCT data & Color Fundus Images of Left & Right Eyes',
 '  Discrete Tone Image Dataset',
 '  News Popularity in Multiple Social Media Platforms',
 '  Ultrasonic flowmeter diagnostics',
 '  ICMLA 2014 Accepted Papers Data Set',
 '  BLE RSSI Dataset for Indoor localization and Navigation',
 '  Container Crane Controller Data Set',
 '  Residential Building Data Set',
 '  Health News in Twitter',
 '  chipseq',
 '  SGEMM GPU kernel performance',
 '  Repeat Consumption Matrices',
 '  detection_of_IoT_botnet_attacks_N_BaIoT',
 '  Absenteeism at work',
 '  SCADI',
 '  Condition monitoring of hydraulic systems',
 '  Carbon Nanotubes',
 '  Optical Interconnection Network',
 '  Sports articles for objectivity analysis',
 '  Breast Cancer Coimbra',
 '  GNFUV Unmanned Surface Vehicles Sensor Data',
 '  Dishonest Internet users Dataset',
 '  Victorian Era Authorship Attribution',
 '  Simulated Falls and Daily Living Activities Data Set',
 '  Multimodal Damage Identification for Humanitarian Computing',
 '  EEG Steady-State Visual Evoked Potential Signals',
 '  Roman Urdu Data Set',
 '  Avila',
 '  PANDOR',
 '  Drug Review Dataset (Druglib.com)',
 '  Drug Review Dataset (Drugs.com)',
 '  Physical Unclonable Functions',
 '  Superconductivty Data',
 '  WESAD (Wearable Stress and Affect Detection)',
 '  GNFUV Unmanned Surface Vehicles Sensor Data Set 2',
 '  Student Academics Performance',
 '  Online Shoppers Purchasing Intention Dataset',
 '  PMU-UD',
 "  Parkinson's Disease Classification",
 '  Electrical Grid Stability Simulated Data',
 '  Caesarian Section Classification Dataset',
 '  BAUM-1',
 '  BAUM-2',
 '  Audit Data',
 '  BuddyMove Data Set',
 '  Real estate valuation data set',
 '  Early biomarkers of Parkinson’s disease based on natural connected speech Data Set',
 '  Somerville Happiness Survey',
 '  2.4 GHZ Indoor Channel Measurements',
 '  EMG data for gestures',
 '  Parking Birmingham',
 '  Behavior of the urban traffic of the city of Sao Paulo in Brazil',
 '  Travel Reviews',
 '  Tarvel Review Ratings',
 '  Rice Leaf Diseases',
 '  Gas sensor array temperature modulation',
 '  Facebook Live Sellers in Thailand',
 '  Parkinson Dataset with replicated acoustic features',
 '  Metro Interstate Traffic Volume',
 '  Query Analytics Workloads Dataset',
 '  Wave Energy Converters',
 '  PPG-DaLiA',
 '  Alcohol QCM Sensor Dataset',
 '  Divorce Predictors data set',
 '  Incident management process enriched event log',
 '  Opinion Corpus for Lebanese Arabic Reviews (OCLAR)',
 '  MEx',
 '  Beijing Multi-Site Air-Quality Data',
 '  Online Retail II',
 '  Hepatitis C Virus (HCV) for Egyptian patients',
 '  QSAR fish toxicity',
 '  QSAR aquatic toxicity',
 '  Human Activity Recognition from Continuous Ambient Sensor Data',
 '  WISDM Smartphone and Smartwatch Activity and Biometrics Dataset',
 '  QSAR oral toxicity',
 '  QSAR androgen receptor',
 '  QSAR Bioconcentration classes dataset',
 '  QSAR fish bioconcentration factor (BCF)',
 '  A study of Asian Religious and Biblical Texts',
 '  Real-time Election Results: Portugal 2019',
 '  Bias correction of numerical prediction model temperature forecast',
 '  Bar Crawl: Detecting Heavy Drinking',
 '  Kitsune Network Attack Dataset',
 '  Shoulder Implant X-Ray Manufacturer Classification',
 '  Speaker Accent Recognition',
 '  Heart failure clinical records',
 '  Deepfakes: Medical Image Tamper Detection',
 '  selfBACK',
 '  South German Credit',
 '  Exasens',
 '  Swarm Behaviour',
 '  Crop mapping using fused optical-radar data set',
 '  BitcoinHeistRansomwareAddressDataset',
 '  Facebook Large Page-Page Network',
 '  Amphibians',
 '  Early stage diabetes risk prediction dataset.',
 '  Turkish Spam V01',
 '  Stock keeping units',
 '  Demand Forecasting for a store',
 '  Detect Malware Types',
 '  Wave Energy Converters',
 '  Youtube cookery channels viewers comments in Hinglish',
 '  Pedestrian in Traffic Dataset',
 '  Cervical Cancer Behavior Risk',
 '  Sattriya_Dance_Single_Hand_Gestures Dataset',
 '  Divorce Predictors data set',
 '  3W dataset',
 '  Malware static and dynamic features VxHeaven and Virus Total',
 '  Internet Firewall Data',
 '  User Profiling and Abusive Language Detection Dataset',
 '  Estimation of obesity levels based on eating habits and physical condition',
 '  Rice (Cammeo and Osmancik)',
 '  Vehicle routing and scheduling problems',
 '  Algerian Forest Fires Dataset',
 '  Breath Metabolomics',
 '  Horton General Hospital',
 '  UrbanGB, urban road accidents coordinates labelled by the urban center',
 '  Gas Turbine CO and NOx Emission Data Set',
 '  Activity recognition using wearable physiological measurements',
 '  clickstream data for online shopping',
 '  CNNpred: CNN-based stock market prediction using a diverse set of variables',
 '  Apartment for rent classified',
 '  : Simulated Data set of Iraqi tourism places',
 '  Nasarian CAD Dataset',
 '  Monolithic Columns in Troad and Mysia Region',
 '  Bar Crawl: Detecting Heavy Drinking',
 '  Seoul Bike Sharing Demand',
 '  Person Classification Gait Data',
 '  Shill Bidding Dataset',
 '  Iranian Churn Dataset',
 '  Unmanned Aerial Vehicle (UAV) Intrusion Detection',
 '  Bone marrow transplant: children',
 '  Exasens',
 '  COVID-19 Surveillance',
 '  Refractive errors',
 '  Shoulder Implant X-Ray Manufacturer Classification',
 '  CLINC150',
 '  HCV data',
 '  Taiwanese Bankruptcy Prediction',
 '  South German Credit (UPDATE)',
 '  IIWA14-R820-Gazebo-Dataset-10Trajectories',
 '  Guitar Chords finger positions',
 '  Russian Corpus of Biographical Texts',
 '  Codon usage',
 '  Intelligent Media Accelerometer and Gyroscope (IM-AccGyro) Dataset',
 '  Myocardial infarction complications',
 '  Hungarian Chickenpox Cases',
 '  Simulated data for survival modelling',
 '  Student Performance on an entrance examination',
 '  Chemical Composition of Ceramic Samples',
 '  Labeled Text Forum Threads Dataset',
 '  Stock keeping units',
 '  BLE RSSI dataset for Indoor localization',
 '  Basketball dataset',
 '  GitHub MUSAE',
 '  Anticancer peptides',
 '  Monolithic Columns in Troad and Mysia Region',
 '  Gender by Name',
 '  Iranian Churn Dataset',
 '  Unmanned Aerial Vehicle (UAV) Intrusion Detection',
 '  Shoulder Implant Manufacture Classification',
 '  LastFM Asia Social Network',
 '  Wheat kernels',
 '  Productivity Prediction of Garment Employees',
 '  Multi-view Brain Networks',
 '  LastFM Asia Social Network',
 '  Wisesight Sentiment Corpus',
 '  AI4I 2020 Predictive Maintenance Dataset',

In [162]:
types=[]
dtype=driver.find_elements("xpath",'//table[@border="1"][1]/tbody/tr/td[2]')
for i in dtype:
    types.append(i.text)
len(types)

623

In [163]:
types

['Data Types',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Univariate, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Univariate, Time-Series ',
 'Multivariate, Spatial ',
 'Multivariate ',
 'Multivariate, Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Data-Generator ',
 ' ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Relational ',
 'Multivariate ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Sequential, Domain-Theory ',
 'Sequential ',
 'Sequential, Domain-Theory ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Domain-Theory ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Data-Generator ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Text ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Relational ',
 'Multivariate, Time-Series ',
 'Spatio-temporal ',
 'Transactional, Sequential ',
 'Image ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Relational ',
 'Multivariate, Relational ',
 'Sequential ',
 'Text ',
 'Multivariate, Time-Series ',
 'Univariate, Time-Series ',
 'Text ',
 'Multivariate, Time-Series ',
 'Time-Series ',
 'Multivariate, Text ',
 'Text, Sequential ',
 'Image ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Domain-Theory ',
 ' ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Text ',
 'Multivariate ',
 'Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate, Time-Series ',
 'Univariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Text ',
 'Domain-Theory ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate, Text, Domain-Theory ',
 'Time-Series, Domain-Theory ',
 'Multivariate, Text, Domain-Theory ',
 'Text ',
 'Text ',
 'Multivariate, Univariate, Text ',
 'Multivariate, Univariate, Text ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Univariate ',
 'Multivariate, Text, Domain-Theory ',
 'Univariate ',
 'Univariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Univariate, Text ',
 'Sequential ',
 'Text ',
 'Multivariate, Time-Series ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Sequential, Text ',
 'Multivariate, Univariate, Time-Series ',
 'Time-Series, Multivariate ',
 'Multivariate ',
 'Sequential ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series, Text ',
 'Univariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 ' ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Univariate, Sequential, Time-Series ',
 'Univariate, Sequential, Time-Series ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Univariate, Domain-Theory ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 ' ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Text ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Univariate, Sequential, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series, Domain-Theory ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series, Domain-Theory ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Text ',
 'Multivariate, Text ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 ' ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 ' ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Time-Series ',
 'Text ',
 ' ',
 ' ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Sequential, Text ',
 'Multivariate, Text ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 ' ',
 'Sequential ',
 'Univariate ',
 'Univariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Univariate, Domain-Theory ',
 'Multivariate ',
 'Text ',
 'Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Univariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Text ',
 'Time-Series ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Univariate ',
 'Multivariate ',
 'Multivariate ',
 'Univariate ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate, Univariate, Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Text ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Univariate ',
 'Multivariate, Sequential ',
 'Text ',
 'Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Time-Series, Text ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series, Text ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Univariate ',
 'Multivariate ',
 'Multivariate, Univariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Univariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Text ',
 'Text ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Sequential, Time-Series ',
 'Time-Series ',
 'Multivariate ',
 'Sequential ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Sequential ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Text ',
 'Univariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Univariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate, Time-Series ',
 'Univariate ']

In [164]:
task=[]
dtsk=driver.find_elements("xpath",'//table[@border="1"][1]/tbody/tr/td[3]')
for i in dtsk:
    task.append(i.text)
len(task)

623

In [165]:
task

['Default Task',
 'Classification ',
 'Classification ',
 'Classification ',
 'Recommender-Systems ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Function-Learning ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Relational-Learning ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Clustering ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Clustering ',
 'Classification ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Recommender-Systems ',
 'Classification ',
 'Regression, Description ',
 ' ',
 ' ',
 'Classification ',
 'Regression ',
 'Classification ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Clustering ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Causal-Discovery ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Causal-Discovery ',
 'Clustering ',
 'Classification, Clustering ',
 'Regression ',
 'Regression ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 ' ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression, Clustering, Causal-Discovery ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Regression, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Regression ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Regression, Clustering ',
 'Classification, Regression ',
 'Regression, Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering, Causa ',
 'Classification, Clustering ',
 'Regression ',
 'Classification ',
 'Regression ',
 'Regression ',
 ' ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering ',
 'Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering, Causal-Discovery ',
 'Classification, Regression, Clustering ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Clustering ',
 'Classification, Regression ',
 'Classification, Regression ',
 'Classification, Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Clustering ',
 'Classification, Regression ',
 'Regression ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Classification ',
 'Classification, Regression ',
 'Regression, Clustering ',
 'Classification, Regression ',
 'Classification, Causal-Discovery ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Regression, Clustering, Causal-Discovery ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Clustering, Causal-Discovery ',
 'Classification, Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Causal-Discovery ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification, Clustering ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Causal-Discovery ',
 'Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification, Clustering, Causal-Discovery ',
 'Classification, Regression ',
 'Classification, Regression, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Causal-Discovery ',
 'Classification, Clustering ',
 'Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Classification ',
 'Regression ',
 'Classification, Regression, Clustering ',
 'Clustering ',
 'Classification, Regression ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Clustering ',
 'Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Regression ',
 'Clustering ',
 'Classification ',
 'Regression ',
 'Clustering ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Recommendation ',
 'Classification, Regression, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Regression ',
 'Classification, Regression ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Regression ',
 'Clustering ',
 'Classification ',
 'Regression ',
 'Regression, Clustering ',
 'Regression ',
 'Regression ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Regression, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Regression ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Regression ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Regression ',
 'Classification, Clustering ',
 'Regression ',
 'Regression ',
 'Classification, Regression ',
 'Classification, Clustering, Causal-Discovery ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Clustering ',
 'Regression ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification, Regression, Causal-Discovery ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Clustering ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Causal-Discovery ',
 'Clustering ',
 'Regression, Clustering ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification, Regression ',
 'Classification, Regression, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Classification ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Causal-Discovery ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Regression ',
 'Regression ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Classification, Regression ',
 'Regression ',
 'Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ']

In [166]:
attype=[]
atyp=driver.find_elements("xpath",'//table[@border="1"][1]/tbody/tr/td[4]')
for i in atyp:
    attype.append(i.text)
len(attype)

623

In [167]:
attype

['Attribute Types',
 'Categorical, Integer, Real ',
 'Categorical, Integer ',
 'Categorical, Integer, Real ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Categorical ',
 'Categorical ',
 'Categorical, Real ',
 'Categorical, Integer, Real ',
 ' ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 'Integer ',
 'Real ',
 'Real ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical, Integer ',
 ' ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical, Real, Integer ',
 'Integer ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Categorical, Integer, Real ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Real ',
 ' ',
 ' ',
 'Categorical, Integer, Real ',
 'Real ',
 'Categorical, Integer ',
 'Real ',
 'Real ',
 'Integer ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Real ',
 'Real ',
 'Categorical, Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical ',
 'Categorical ',
 'Integer ',
 'Categorical, Integer, Real ',
 ' ',
 'Integer ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 ' ',
 'Integer, Real ',
 'Categorical ',
 'Integer ',
 'Integer ',
 'Categorical ',
 ' ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 'Categorical, Integer ',
 'Categorical ',
 ' ',
 ' ',
 'Real ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 'Integer ',
 'Integer, Real ',
 'Integer, Real ',
 'Categorical ',
 'Integer ',
 'Categorical, Integer ',
 ' ',
 ' ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical, Real ',
 'Categorical ',
 'Categorical, Integer ',
 'Categorical ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Categorical, Integer ',
 ' ',
 ' ',
 'Categorical, Real ',
 'Real ',
 'Categorical ',
 'Categorical, Integer ',
 'Categorical, Real ',
 'Real ',
 ' ',
 'Categorical, Integer, Real ',
 'Integer, Real ',
 'Categorical ',
 'Integer ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Real ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 ' ',
 ' ',
 'Categorical ',
 ' ',
 'Categorical, Real ',
 ' ',
 'Categorical ',
 'Integer ',
 'Real ',
 'Categorical ',
 ' ',
 ' ',
 'Categorical, Integer, Real ',
 'Categorical, Integer ',
 'Categorical, Real ',
 'Integer ',
 'Real ',
 'Integer ',
 'Integer ',
 'Categorical ',
 'Real ',
 'Real ',
 ' ',
 ' ',
 'Real ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Real ',
 'Integer ',
 'Integer ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Real ',
 'Categorical ',
 'Real ',
 'Real ',
 'Real ',
 'Categorical, Integer ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Categorical, Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 ' ',
 ' ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 ' ',
 ' ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Integer ',
 'Real ',
 ' ',
 ' ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 ' ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 'Real ',
 'Integer ',
 ' ',
 'Real ',
 ' ',
 'Integer ',
 ' ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 ' ',
 ' ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Categorical ',
 ' ',
 'Integer, Real ',
 ' ',
 ' ',
 'Integer, Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Integer ',
 ' ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 ' ',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Integer ',
 ' ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 ' ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 'Real ',
 ' ',
 ' ',
 'Integer ',
 'Integer ',
 'Integer ',
 ' ',
 'Real ',
 'Categorical ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Integer, Real ',
 ' ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 ' ',
 ' ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Integer ',
 ' ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 ' ',
 ' ',
 ' ',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Integer, Real ',
 ' ',
 ' ',
 'Integer, Real ',
 'Integer ',
 ' ',
 'Real ',
 ' ',
 'Real ',
 'Integer ',
 ' ',
 'Integer ',
 'Integer, Real ',
 'Integer, Real ',
 ' ',
 ' ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 ' ',
 ' ',
 ' ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 ' ',
 'Integer ',
 'Real ',
 ' ',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Integer ',
 ' ',
 ' ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 ' ',
 ' ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 ' ',
 ' ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 ' ',
 ' ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Integer, Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 ' ',
 'Integer, Real ',
 'Integer, Real ',
 ' ',
 'Integer ',
 'Integer ',
 'Real ',
 ' ',
 ' ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer ',
 ' ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Integer, Real ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Real ']

In [168]:
instances=[]
no_inst=driver.find_elements("xpath",'//table[@border="1"][1]/tbody/tr/td[5]')
for i in no_inst:
    instances.append(i.text)
len(instances)

623

In [169]:
instances

['# Instances',
 '4177 ',
 '48842 ',
 '798 ',
 '37711 ',
 '452 ',
 '6000 ',
 '226 ',
 '226 ',
 '398 ',
 '205 ',
 '294 ',
 '625 ',
 '16 ',
 '286 ',
 '699 ',
 '198 ',
 '569 ',
 '108 ',
 '1728 ',
 '48842 ',
 ' ',
 '3196 ',
 '28056 ',
 ' ',
 '100 ',
 '67557 ',
 '690 ',
 '125 ',
 '209 ',
 '1473 ',
 '581012 ',
 '512 ',
 '366 ',
 ' ',
 ' ',
 ' ',
 ' ',
 '132 ',
 '336 ',
 '194 ',
 '352 ',
 '214 ',
 '306 ',
 '160 ',
 '303 ',
 '155 ',
 '368 ',
 ' ',
 '2310 ',
 '3279 ',
 '351 ',
 '150 ',
 '7797 ',
 '104 ',
 '57 ',
 ' ',
 '24 ',
 '20000 ',
 '345 ',
 ' ',
 '32 ',
 '148 ',
 '209 ',
 '528 ',
 ' ',
 '106 ',
 '128 ',
 '3190 ',
 '432 ',
 '202 ',
 '2000 ',
 '8124 ',
 '476 ',
 '6598 ',
 '12960 ',
 ' ',
 '5473 ',
 '5620 ',
 '10992 ',
 '90 ',
 '339 ',
 ' ',
 ' ',
 ' ',
 '167 ',
 '15 ',
 '1389 ',
 '307 ',
 '47 ',
 '23 ',
 '531 ',
 '4601 ',
 '267 ',
 '267 ',
 '76 ',
 ' ',
 '1000 ',
 '151 ',
 '958 ',
 '7200 ',
 '10 ',
 '285 ',
 '435 ',
 '527 ',
 '5000 ',
 '5000 ',
 '178 ',
 '1484 ',
 '101 ',
 ' ',
 '20000 ',
 '6650 ',
 '2565 ',
 '2458285 ',
 '299285 ',
 '340 ',
 '68040 ',
 ' ',
 '122 ',
 '178080 ',
 '50672 ',
 '640 ',
 '9000 ',
 '10104 ',
 '256932 ',
 '640 ',
 '191779 ',
 '4000000 ',
 ' ',
 '10000 ',
 '989818 ',
 '129000 ',
 ' ',
 '100000 ',
 '21578 ',
 '463 ',
 '600 ',
 '332 ',
 ' ',
 ' ',
 '690 ',
 '1000 ',
 '270 ',
 '6435 ',
 '2310 ',
 '58000 ',
 '946 ',
 '20008 ',
 '208 ',
 '528 ',
 ' ',
 ' ',
 '1024 ',
 '10080 ',
 '50400 ',
 '1025010 ',
 '19020 ',
 '1364 ',
 '961 ',
 '517 ',
 '200 ',
 '8000000 ',
 '1030 ',
 '606 ',
 '900 ',
 '2600 ',
 '1950 ',
 '13500 ',
 '4400 ',
 '2536 ',
 '300 ',
 '197 ',
 '2858 ',
 '748 ',
 '11640 ',
 '1593 ',
 '1567 ',
 '22632 ',
 '360 ',
 '103 ',
 '1994 ',
 '120 ',
 '4898 ',
 '2396130 ',
 '16772 ',
 '5875 ',
 '503 ',
 '51 ',
 '106 ',
 '2126 ',
 '5456 ',
 '8800 ',
 '164860 ',
 ' ',
 '1941 ',
 '130065 ',
 '515345 ',
 '440 ',
 ' ',
 '53500 ',
 '8235 ',
 ' ',
 '5749132 ',
 '2215 ',
 '310 ',
 '10000 ',
 '3000 ',
 '1500 ',
 '30000 ',
 '2500 ',
 '4143 ',
 '64 ',
 '53414 ',
 '65554 ',
 '45211 ',
 '1138562 ',
 '13910 ',
 '583 ',
 '2551 ',
 '34465 ',
 '5574 ',
 '245057 ',
 '182 ',
 '3850505 ',
 '138 ',
 '1080 ',
 '2075259 ',
 '210 ',
 '115 ',
 '3960456 ',
 ' ',
 '10299 ',
 '1600 ',
 '768 ',
 '308 ',
 '100 ',
 '237 ',
 '434874 ',
 '536 ',
 '140000 ',
 '6118 ',
 '165632 ',
 '18000 ',
 '540 ',
 '931 ',
 '1055 ',
 '100 ',
 '9120 ',
 '403 ',
 '111740 ',
 '10421 ',
 '5820 ',
 '403 ',
 '14980 ',
 '45730 ',
 '2584 ',
 '1372 ',
 '306 ',
 '120000 ',
 '13910 ',
 '2747 ',
 '3395 ',
 '39242 ',
 '4137 ',
 '17389 ',
 '51 ',
 '470 ',
 '132 ',
 '5000000 ',
 '11000000 ',
 '250 ',
 '126 ',
 ' ',
 '4889 ',
 ' ',
 ' ',
 '340 ',
 '501 ',
 '45781 ',
 '1503 ',
 '440 ',
 '2000 ',
 '9568 ',
 '168 ',
 '100000 ',
 '5665 ',
 '79 ',
 '127 ',
 '1040 ',
 '9900 ',
 '560 ',
 '60021 ',
 '1419 ',
 '101 ',
 '399 ',
 '58 ',
 '180 ',
 '21048 ',
 ' ',
 '750 ',
 '3000 ',
 '150 ',
 '1059 ',
 '11934 ',
 '27965 ',
 '216 ',
 '120 ',
 '649 ',
 '370 ',
 '4178504 ',
 '221579 ',
 '10800 ',
 '58509 ',
 '129685 ',
 '2456 ',
 '2921 ',
 '1151 ',
 '6590 ',
 '3000 ',
 '39797 ',
 '326 ',
 '913 ',
 '168286 ',
 '400 ',
 '314080 ',
 '637 ',
 '1710671 ',
 '12000 ',
 '10929 ',
 '1080 ',
 '40000 ',
 '43930257 ',
 '230318 ',
 '10500000 ',
 '13197 ',
 ' ',
 '30000 ',
 '324 ',
 '541909 ',
 '11164866 ',
 '163 ',
 '373 ',
 '20560 ',
 '40 ',
 '422937 ',
 '9358 ',
 '640 ',
 '919438 ',
 '40949 ',
 '5744 ',
 '10503 ',
 '42240 ',
 '102944 ',
 '500 ',
 '9782222 ',
 '11463 ',
 '17898 ',
 '1885 ',
 '19735 ',
 '1540 ',
 '4007 ',
 '153540 ',
 '606 ',
 '1353 ',
 '1956 ',
 '43824 ',
 '3942 ',
 '858 ',
 '287 ',
 '17764280 ',
 '106574 ',
 '9358 ',
 '11500 ',
 '92000 ',
 '315 ',
 '78095 ',
 '130 ',
 '74 ',
 '52854 ',
 '77 ',
 '811 ',
 '504 ',
 '401 ',
 '2856 ',
 '10546 ',
 '801 ',
 '1540 ',
 '1451 ',
 '1075 ',
 '78095 ',
 '7195 ',
 '3600 ',
 '76 ',
 '60 ',
 '405 ',
 '303 ',
 '303 ',
 '107888 ',
 '76000 ',
 '10000 ',
 '180 ',
 '745000 ',
 '12234 ',
 '292 ',
 '104 ',
 '60000 ',
 '2000 ',
 '165 ',
 '217 ',
 '1175 ',
 '704 ',
 '75128 ',
 '90 ',
 '90 ',
 '50 ',
 '71 ',
 '93239 ',
 '540 ',
 '105 ',
 '6611 ',
 '15 ',
 '372 ',
 '58000 ',
 '4960 ',
 '241600 ',
 '130000 ',
 '7062606 ',
 '740 ',
 '70 ',
 '2205 ',
 '10721 ',
 '640 ',
 '1000 ',
 '116 ',
 '1672 ',
 '322 ',
 '93600 ',
 '3060 ',
 '5879 ',
 '9200 ',
 '20000 ',
 '20867 ',
 ' ',
 '4143 ',
 '215063 ',
 '6000000 ',
 '21263 ',
 '63000000 ',
 '10190 ',
 '300 ',
 '12330 ',
 '5180 ',
 '756 ',
 '10000 ',
 '80 ',
 '1184 ',
 '1047 ',
 '777 ',
 '249 ',
 '414 ',
 ' ',
 '143 ',
 '7840 ',
 '30000 ',
 '35717 ',
 '135 ',
 '980 ',
 '5456 ',
 '120 ',
 '4095000 ',
 '7051 ',
 '240 ',
 '48204 ',
 '260000 ',
 '288000 ',
 '8300000 ',
 '125 ',
 '170 ',
 '141712 ',
 '3916 ',
 '6262 ',
 '420768 ',
 '1067371 ',
 '1385 ',
 '908 ',
 '546 ',
 '13956534 ',
 '15630426 ',
 '8992 ',
 '1687 ',
 '779 ',
 '1056 ',
 '590 ',
 '21643 ',
 '7750 ',
 '14057567 ',
 '27170754 ',
 '597 ',
 '329 ',
 '299 ',
 '20000 ',
 '26136 ',
 '1000 ',
 '399 ',
 '24017 ',
 '325834 ',
 '2916697 ',
 '22470 ',
 '189 ',
 '520 ',
 '826 ',
 '2279 ',
 '28764 ',
 '7107 ',
 '288000 ',
 '9800 ',
 '4760 ',
 '72 ',
 '1450 ',
 '170 ',
 '1984 ',
 '2955 ',
 '65532 ',
 '65919 ',
 '2111 ',
 '3810 ',
 '18 ',
 '244 ',
 '104 ',
 '139 ',
 '360177 ',
 '36733 ',
 '4480 ',
 '165474 ',
 '1985 ',
 '10000 ',
 '232 ',
 '150 ',
 '11 ',
 '14057567 ',
 '8760 ',
 '48 ',
 '6321 ',
 '3150 ',
 '17256 ',
 '187 ',
 '399 ',
 '14 ',
 '467 ',
 '597 ',
 '23700 ',
 '615 ',
 '6819 ',
 '1000 ',
 ' ',
 '2633 ',
 '200 ',
 '13028 ',
 '800 ',
 '1700 ',
 '521 ',
 '120000 ',
 '666 ',
 '88 ',
 '200 ',
 '2279 ',
 '23570 ',
 '10000 ',
 '37700 ',
 '1850 ',
 '11 ',
 '147270 ',
 '3150 ',
 '17256 ',
 '597 ',
 '7624 ',
 '314 ',
 '1197 ',
 '70 ',
 '7624 ',
 '26737 ',
 '10000 ',
 '13611 ',
 '12684 ',
 '48 ',
 '731 ',
 '731 ',
 '557 ',
 '107 ',
 '158716 ',
 '15744 ',
 '153000 ',
 '557 ',
 '36 ',
 '4200 ',
 '61069 ',
 '52417 ',
 '900 ',
 '35040 ',
 '4746 ',
 '73 ',
 '11000 ',
 '4465 ',
 '145 ',
 '202 ',
 '221 ',
 '597 ',
 '298 ',
 '110341 ',
 '705 ',
 '2101 ',
 '1765 ',
 '150 ',
 '4000 ',
 '6272 ',
 '1996 ',
 '35040 ',
 '75840 ',
 '400 ',
 '1014 ',
 '10129 ',
 '4000 ']

In [170]:
attributes=[]
no_attr=driver.find_elements("xpath",'//table[@border="1"][1]/tbody/tr/td[6]')
for i in no_attr:
    attributes.append(i.text)
len(attributes)

623

In [171]:
attributes

['# Attributes',
 '8 ',
 '14 ',
 '38 ',
 '294 ',
 '279 ',
 '7 ',
 ' ',
 '69 ',
 '8 ',
 '26 ',
 '1 ',
 '4 ',
 '4 ',
 '9 ',
 '10 ',
 '34 ',
 '32 ',
 '13 ',
 '6 ',
 '14 ',
 '22 ',
 '36 ',
 '6 ',
 ' ',
 '6 ',
 '42 ',
 '15 ',
 ' ',
 '9 ',
 '9 ',
 '54 ',
 '39 ',
 '33 ',
 '20 ',
 ' ',
 ' ',
 ' ',
 '12 ',
 '8 ',
 '30 ',
 ' ',
 '10 ',
 '3 ',
 '5 ',
 '75 ',
 '19 ',
 '27 ',
 ' ',
 '19 ',
 '1558 ',
 '34 ',
 '4 ',
 '617 ',
 '12 ',
 '16 ',
 '7 ',
 '4 ',
 '16 ',
 '7 ',
 ' ',
 '56 ',
 '18 ',
 '8 ',
 '22 ',
 ' ',
 '58 ',
 ' ',
 '61 ',
 '7 ',
 ' ',
 '649 ',
 '22 ',
 '168 ',
 '168 ',
 '8 ',
 ' ',
 '10 ',
 '64 ',
 '16 ',
 '8 ',
 '17 ',
 ' ',
 ' ',
 '72 ',
 '4 ',
 '6 ',
 '10 ',
 '35 ',
 '35 ',
 '4 ',
 '102 ',
 '57 ',
 '22 ',
 '44 ',
 '45 ',
 ' ',
 ' ',
 '5 ',
 '9 ',
 '21 ',
 '32 ',
 '17 ',
 '16 ',
 '38 ',
 '21 ',
 '40 ',
 '13 ',
 '8 ',
 '17 ',
 ' ',
 ' ',
 '15 ',
 '22 ',
 '68 ',
 '40 ',
 '17 ',
 '89 ',
 ' ',
 '4 ',
 '12 ',
 ' ',
 ' ',
 '86 ',
 '72 ',
 '61 ',
 '12 ',
 '481 ',
 '42 ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '5 ',
 '90 ',
 ' ',
 '5 ',
 ' ',
 ' ',
 '14 ',
 '20 ',
 '13 ',
 '36 ',
 '19 ',
 '9 ',
 '18 ',
 '4 ',
 '60 ',
 '10 ',
 ' ',
 ' ',
 '10 ',
 '4 ',
 '3 ',
 '11 ',
 '11 ',
 ' ',
 '6 ',
 '13 ',
 ' ',
 '100000 ',
 '9 ',
 '101 ',
 '10000 ',
 '20000 ',
 '100000 ',
 '5000 ',
 '500 ',
 '73 ',
 '43 ',
 '23 ',
 '3 ',
 '5 ',
 ' ',
 '256 ',
 '591 ',
 '70 ',
 '91 ',
 '10 ',
 '128 ',
 '6 ',
 '12 ',
 '3231961 ',
 '5409 ',
 '26 ',
 ' ',
 ' ',
 '10 ',
 '23 ',
 '24 ',
 '13 ',
 '8 ',
 ' ',
 '27 ',
 '50 ',
 '90 ',
 '138672 ',
 ' ',
 '386 ',
 ' ',
 ' ',
 '12 ',
 '147 ',
 '6 ',
 '8 ',
 '27 ',
 '10000 ',
 '20000 ',
 '10000 ',
 '54877 ',
 '4702 ',
 '24 ',
 '29 ',
 '17 ',
 '3 ',
 '128 ',
 '10 ',
 '242 ',
 '120 ',
 ' ',
 '4 ',
 '13 ',
 '52 ',
 '47 ',
 '857 ',
 '9 ',
 '7 ',
 '200 ',
 '4 ',
 ' ',
 '561 ',
 '64 ',
 '8 ',
 '7 ',
 '10 ',
 '9 ',
 '4 ',
 '8 ',
 '77 ',
 '51 ',
 '18 ',
 '1950000 ',
 '18 ',
 '1300 ',
 '41 ',
 '6 ',
 '5625 ',
 '5 ',
 ' ',
 '7 ',
 '33 ',
 '5 ',
 '15 ',
 '9 ',
 '19 ',
 '5 ',
 '5 ',
 '1000000 ',
 '129 ',
 ' ',
 '20 ',
 '152 ',
 '24 ',
 '16 ',
 '35 ',
 '17 ',
 '5 ',
 '18 ',
 '28 ',
 '7 ',
 '309 ',
 '3 ',
 '6 ',
 ' ',
 ' ',
 '16 ',
 '13 ',
 '5 ',
 '6 ',
 '8 ',
 '2 ',
 '4 ',
 '148 ',
 '55 ',
 '17 ',
 '8 ',
 '42 ',
 '26 ',
 '50 ',
 '2 ',
 '281 ',
 '120 ',
 ' ',
 '6 ',
 '120432 ',
 '150000 ',
 '529 ',
 ' ',
 '16 ',
 '2500 ',
 '5 ',
 '68 ',
 '16 ',
 '100 ',
 '216 ',
 '23 ',
 '33 ',
 '140256 ',
 '19 ',
 '20 ',
 '20 ',
 '49 ',
 '12 ',
 '30 ',
 '5232 ',
 '20 ',
 '1 ',
 ' ',
 '61 ',
 '27 ',
 '53 ',
 '11 ',
 '25 ',
 '0 ',
 '20 ',
 '9 ',
 '3 ',
 '561 ',
 '82 ',
 '13 ',
 '16 ',
 '13 ',
 '28 ',
 '4 ',
 ' ',
 '24 ',
 '34 ',
 '8 ',
 '128 ',
 '15 ',
 '513 ',
 '7 ',
 '7 ',
 '5 ',
 '15 ',
 '480000 ',
 '11 ',
 '54 ',
 '561 ',
 '64 ',
 '6 ',
 '116 ',
 '19 ',
 ' ',
 '5812 ',
 '9 ',
 '32 ',
 '29 ',
 '67 ',
 ' ',
 '25 ',
 '6400 ',
 '10 ',
 '5 ',
 '13 ',
 '98 ',
 '36 ',
 '69 ',
 '2158859 ',
 '518 ',
 '15 ',
 '179 ',
 ' ',
 '12 ',
 '38 ',
 '65 ',
 '102 ',
 '86 ',
 '7 ',
 '53 ',
 '20 ',
 '1 ',
 '71 ',
 '29 ',
 '20531 ',
 '65 ',
 '3 ',
 '22 ',
 '38 ',
 '22 ',
 '4814 ',
 '698 ',
 '13 ',
 '10 ',
 '59 ',
 '56 ',
 '482 ',
 '171 ',
 '5 ',
 '500 ',
 '411 ',
 '8519 ',
 '21 ',
 '21 ',
 '171 ',
 '7 ',
 '49 ',
 '12 ',
 '3 ',
 '21 ',
 '9 ',
 '8 ',
 '7 ',
 '2 ',
 '11 ',
 '11 ',
 '173 ',
 '5 ',
 '15 ',
 '3 ',
 '105 ',
 '25000 ',
 ' ',
 '18 ',
 '21000 ',
 '115 ',
 '21 ',
 '206 ',
 '43680 ',
 '8 ',
 '10 ',
 '59 ',
 '10 ',
 '5 ',
 '5 ',
 '1000 ',
 '138 ',
 ' ',
 '16 ',
 '2 ',
 '10 ',
 ' ',
 '8 ',
 '6 ',
 '129 ',
 '81 ',
 '12 ',
 '6 ',
 '22 ',
 '18 ',
 '9 ',
 '754 ',
 '14 ',
 '5 ',
 ' ',
 ' ',
 '18 ',
 '7 ',
 '7 ',
 ' ',
 '7 ',
 '5 ',
 '6 ',
 '4 ',
 '18 ',
 '11 ',
 '25 ',
 ' ',
 '20 ',
 '12 ',
 '46 ',
 '9 ',
 '8 ',
 '49 ',
 '11 ',
 '8 ',
 '54 ',
 '36 ',
 '3916 ',
 '710 ',
 '18 ',
 '8 ',
 '29 ',
 '7 ',
 '9 ',
 '37 ',
 '6 ',
 '1024 ',
 '1024 ',
 '14 ',
 '7 ',
 '8265 ',
 '29 ',
 '25 ',
 '3 ',
 '115 ',
 '1 ',
 '12 ',
 '13 ',
 '200000 ',
 '6 ',
 '21 ',
 '4 ',
 '2400 ',
 '175 ',
 '10 ',
 '4714 ',
 '23 ',
 '17 ',
 '2 ',
 '9 ',
 '8 ',
 '280 ',
 '49 ',
 '3 ',
 '14 ',
 '19 ',
 ' ',
 '54 ',
 '8 ',
 '1087 ',
 '12 ',
 '3 ',
 '17 ',
 '8 ',
 '9 ',
 '12 ',
 '1656 ',
 '6 ',
 '2 ',
 '11 ',
 '533 ',
 '14 ',
 '84 ',
 '22 ',
 '16 ',
 '52 ',
 '19 ',
 '3 ',
 '14 ',
 '321 ',
 '13 ',
 '13 ',
 '55 ',
 '39 ',
 '4 ',
 '7 ',
 '79 ',
 '1 ',
 ' ',
 '14 ',
 '96 ',
 '21 ',
 ' ',
 '5 ',
 '2 ',
 '69 ',
 '9 ',
 '124 ',
 '20 ',
 '25 ',
 '11 ',
 '19 ',
 '9 ',
 '9 ',
 '5 ',
 '7 ',
 '4006 ',
 '2 ',
 '19 ',
 '4 ',
 '13 ',
 '55 ',
 '1 ',
 '7842 ',
 '15 ',
 '15 ',
 '70 ',
 '7842 ',
 '4 ',
 '14 ',
 '17 ',
 '23 ',
 '321 ',
 '1068 ',
 '1068 ',
 '5 ',
 '6 ',
 '4 ',
 ' ',
 '5 ',
 '5 ',
 '15 ',
 '7 ',
 '21 ',
 '9 ',
 '8 ',
 '11 ',
 '21 ',
 '22 ',
 '2 ',
 '241 ',
 '33 ',
 '29 ',
 '7 ',
 '1 ',
 ' ',
 '4 ',
 '11 ',
 '47 ',
 '10 ',
 '3 ',
 '2 ',
 '632 ',
 '6826 ',
 '11 ',
 '525 ',
 '50 ',
 '7 ',
 '16 ',
 '2 ']

In [172]:
year=[]
yrs=driver.find_elements("xpath",'//table[@border="1"][1]/tbody/tr/td[7]')
for i in yrs:
    year.append(i.text)
len(year)

623

In [173]:
year

['Year',
 '1995 ',
 '1996 ',
 ' ',
 '1998 ',
 '1998 ',
 '1992 ',
 '1987 ',
 '1992 ',
 '1993 ',
 '1987 ',
 '1994 ',
 '1994 ',
 ' ',
 '1988 ',
 '1992 ',
 '1995 ',
 '1995 ',
 '1990 ',
 '1997 ',
 '1996 ',
 '1988 ',
 '1989 ',
 '1994 ',
 ' ',
 ' ',
 '1995 ',
 ' ',
 '1992 ',
 '1987 ',
 '1997 ',
 '1998 ',
 '1995 ',
 '1998 ',
 ' ',
 ' ',
 '1994 ',
 ' ',
 '1989 ',
 '1996 ',
 '1990 ',
 '1990 ',
 '1987 ',
 '1999 ',
 '1989 ',
 '1988 ',
 '1988 ',
 '1989 ',
 ' ',
 '1990 ',
 '1998 ',
 '1989 ',
 '1988 ',
 '1994 ',
 '1990 ',
 '1988 ',
 '1988 ',
 '1990 ',
 '1991 ',
 '1990 ',
 ' ',
 '1992 ',
 '1988 ',
 '1990 ',
 '1996 ',
 '1995 ',
 '1990 ',
 ' ',
 '1992 ',
 '1992 ',
 '1994 ',
 ' ',
 '1987 ',
 '1994 ',
 '1994 ',
 '1997 ',
 '1991 ',
 '1995 ',
 '1998 ',
 '1998 ',
 '1993 ',
 '1988 ',
 ' ',
 ' ',
 '1992 ',
 '1993 ',
 '1988 ',
 '1989 ',
 '1988 ',
 '1987 ',
 '1993 ',
 '1988 ',
 '1999 ',
 '2001 ',
 '2001 ',
 ' ',
 '1992 ',
 '1993 ',
 '1997 ',
 '1991 ',
 '1987 ',
 '1994 ',
 '1988 ',
 '1987 ',
 '1993 ',
 '1988 ',
 '1988 ',
 '1991 ',
 '1996 ',
 '1990 ',
 ' ',
 '1999 ',
 '1999 ',
 '2002 ',
 ' ',
 '2000 ',
 '1999 ',
 '1999 ',
 '2001 ',
 '1999 ',
 '1999 ',
 '2000 ',
 '1999 ',
 '2000 ',
 '1999 ',
 '1999 ',
 ' ',
 '1998 ',
 '1999 ',
 '2001 ',
 '1999 ',
 ' ',
 '2003 ',
 '1999 ',
 '1999 ',
 '1997 ',
 '1999 ',
 '1999 ',
 '1998 ',
 ' ',
 ' ',
 ' ',
 '1994 ',
 ' ',
 '1993 ',
 '1990 ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '1989 ',
 '2006 ',
 '2006 ',
 '2007 ',
 '2007 ',
 '2007 ',
 '2007 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2007 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2009 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2009 ',
 '2009 ',
 '2009 ',
 '2009 ',
 '2009 ',
 '2009 ',
 '2010 ',
 '2009 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2014 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2013 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2015 ',
 '2014 ',
 '2014 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2014 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2016 ',
 '2016 ',
 '2015 ',
 '2016 ',
 '2016 ',
 '2015 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2018 ',
 '2018 ',
 '2016 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2019 ',
 '2019 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2021 ',
 '2018 ',
 '2018 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2021 ',
 '2021 ']

In [174]:
df=pd.DataFrame({'Dataset Name':name,'Data Type':types,'Task':task,'Attribute Type':attype,'No. of Instances':instances,'No. of Attribute':attributes,'Year':year})
df

,Dataset Name,Data Type,Task,Attribute Type,No. of Instances,No. of Attribute,Year
0,Name,Data Types,Default Task,Attribute Types,# Instances,# Attributes,Year
1,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
2,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
3,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
4,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
...,...,...,...,...,...,...,...
618,Influenza outbreak event prediction via Twit...,Multivariate,Classification,"Integer, Real",75840,525,2020
619,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
620,Maternal Health Risk Data Set,,Classification,,1014,7,2020
621,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
622,Image Recognition Task Execution Times in Mo...,Univariate,Regression,Real,4000,2,2021

In [175]:
driver.close()

#

# THANK YOU